/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package newpackage;

import material.design.buttonRounderC;

/**
 *
 * @author pc
 */
public class pabButton extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public pabButton() {
        initComponents();
    }

    public buttonRounderC getBtnAdd() {
        return btnAdd;
    }

    public buttonRounderC getBtnDelete() {
        return btnDelete;
    }

    public buttonRounderC getBtnMinus() {
        return btnMinus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnMinus = new material.design.buttonRounderC();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnAdd = new material.design.buttonRounderC();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnDelete = new material.design.buttonRounderC();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        add(filler1);

        btnMinus.setBackground(new java.awt.Color(204, 204, 204));
        btnMinus.setText("-");
        add(btnMinus);
        add(filler3);

        btnAdd.setBackground(new java.awt.Color(51, 204, 0));
        btnAdd.setText("+");
        add(btnAdd);
        add(filler2);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("/");
        add(btnDelete);
        add(filler4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounderC btnAdd;
    private material.design.buttonRounderC btnDelete;
    private material.design.buttonRounderC btnMinus;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    // End of variables declaration//GEN-END:variables
}
