/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.autosuggestextefield;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author pc
 */
public class NewJDialog1 extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog1
     */
    public NewJDialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // تجهيز بيانات تجريبية وفحص المكون
        List<String> mockData = new ArrayList<>();
        mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("ثلاجات");
         mockData.add("شاشات");
        mockData.add("مكيفات");
         mockData.add("frigo");
         mockData.add("tv");
        mockData.add("machin");
         mockData.add("pc");
        mockData.add("غسالات");
        mockData.add("شاشات");
        mockData.add("aaaa");
        
        // تمرير البيانات للـ AutoSuggestTextField
                catego.setDictionary(mockData);
                autoSuggestTextField1.setDictionary(mockData);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoSuggestTextField2 = new ui.autosuggestextefield.AutoSuggestTextField();
        textFieldRound1 = new ui.card.TextFieldRound();
        catego = new ui.autosuggestextefield.AutoSuggestTextField1();
        autoSuggestTextField1 = new ui.autosuggestextefield.AutoSuggestTextField();
        jButton1 = new javax.swing.JButton();

        autoSuggestTextField2.setText("autoSuggestTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textFieldRound1.setForeground(new java.awt.Color(215, 233, 255));
        textFieldRound1.setText("textFieldRound1");

        catego.setLabelText("النوعية  Categorie ");

        autoSuggestTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSuggestTextField1ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(12, 174, 12));
        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoSuggestTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(catego, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(textFieldRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)))
                .addComponent(catego, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(autoSuggestTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void autoSuggestTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoSuggestTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoSuggestTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog1 dialog = new NewJDialog1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.autosuggestextefield.AutoSuggestTextField autoSuggestTextField1;
    private ui.autosuggestextefield.AutoSuggestTextField autoSuggestTextField2;
    private ui.autosuggestextefield.AutoSuggestTextField1 catego;
    private javax.swing.JButton jButton1;
    private ui.card.TextFieldRound textFieldRound1;
    // End of variables declaration//GEN-END:variables
}
