/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.card;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author pc
 */
public class panRound extends javax.swing.JPanel {

     
   private Color color1; 
   private Color color2;
   
    public panRound() {
       
      
        initComponents();
        setOpaque(false);
        color1 = Color.BLACK;
        color2= Color.WHITE;
    
    }
      public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    public Color getColor1() {
        return color1;
    }

    public Color getColor2() {
        return color2;
    }
    @Override

protected void paintComponent(Graphics grphcs) {
    super.paintComponent(grphcs);

    Graphics2D g2 = (Graphics2D) grphcs.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
            RenderingHints.VALUE_ANTIALIAS_ON);

    int shadowSize = 9;
    int arc = 25;

    // ==========================
    // Shadow (Right & Bottom)
    // ==========================
    for (int i = shadowSize; i >= 1; i--) {
        g2.setColor(new Color(0, 0, 0, 6));

        g2.fillRoundRect(
                i,
                i,
                getWidth() - shadowSize,
                getHeight() - shadowSize,
                arc,
                arc);
    }

    // ==========================
    // Background
    // ==========================
    GradientPaint gp = new GradientPaint(
            0, 0, color1,
            0, getHeight(), color2);

    g2.setPaint(gp);
    g2.fillRoundRect(
            0,
            0,
            getWidth() - shadowSize,
            getHeight() - shadowSize,
            arc,
            arc);

    // ==========================
    // Border
    // ==========================
    g2.setColor(new Color (230,230,230)); //new Color(230, 232, 236)); // #E6E8EC
   g2.setStroke(new BasicStroke(2f)); 
    g2.drawRoundRect(
            0,
            0,
            getWidth() - shadowSize - 1,
            getHeight() - shadowSize - 1,
            arc,
            arc);

    g2.dispose();
}
//    protected void paintComponent(Graphics grphcs) {
//        Graphics2D g2 = (Graphics2D) grphcs;
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        GradientPaint g =new GradientPaint(0, 0,color1,0,getHeight(),color2);
//        g2.setPaint(g);
//       // g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
//       g2.fillRoundRect(0, 0, getWidth() , getHeight() , 25 , 20); 
//      
//        
//        //cercl white transparent
//        
////        g2.setColor(new Color(255,255,255,50));
////        g2.fillOval(getWidth()-(getHeight()/2), 10, getHeight() , getHeight());
////        g2.fillOval(getWidth()-(getHeight()/2)-20, getHeight()/2+20, getHeight() , getHeight());
//
//        super.paintComponent(grphcs); 
//        
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
