/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import Reports.PrintingService;
import Reports.ReportNames;
import config.DatabaseConnection;
import dao.impl.EntrepriseDAOImpl;
import dao.impl.VersementEntrepriseDAOImpl;
import entity.Entreprise;
import entity.VersementEntreprise;
import frame.AddCompany;
import frame.AllVersementCreditVent;
import frame.ModifyCompany;
import frame.VersementEntrepriseForme;
import home.HomeForm;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import material.design.designeTable;

public class pan_Entreprise extends javax.swing.JPanel {

    HomeForm homeForm;
    Connection connection;
    EntrepriseDAOImpl entrepriseDAOImpl;
    VersementEntrepriseDAOImpl versementEntrepriseDAOImpl;
    PrintingService service_print = new PrintingService();
    Map<String, Object> params = new HashMap<>();
    ValidationMessageDialog validationMessageDialog;
    MessageDialog messageDialog;
    Exite exite;

    public pan_Entreprise(HomeForm homeForm) {
        this.homeForm = homeForm;
        initComponents();
        connection = DatabaseConnection.getInstance().getConnection();
        entrepriseDAOImpl = new EntrepriseDAOImpl(connection);
        versementEntrepriseDAOImpl= new VersementEntrepriseDAOImpl(connection);
        validationMessageDialog = new ValidationMessageDialog(homeForm);
        exite = new Exite(homeForm);
        messageDialog = new MessageDialog(homeForm);

        new designeTable().SearchTable(tab, txt_search);
        new designeTable().setDesignTable(tab, jScrollPane2);
        TableColumn column = tab.getColumnModel().getColumn(0);
        tab.getColumnModel().removeColumn(column);

        setEntreprisesOnTab();

        print();

    }

    private void print() {
        btnImp.addPopupItem("قـائـمـة  الـشـركـات", e -> {
            //ListEnterprises
            params = new HashMap<>();
            service_print.printReport(ReportNames.LIST_ENTERPRISES, params);
        });

        btnImp.addPopupItem("قـائـمـة مـدفـوعـات كل الـشـركـات", e -> {
            params = new HashMap<>();
            //ALL_VERSEMENT_ENTERPRISES
            service_print.printReport(ReportNames.ALL_VERSEMENT_ENTERPRISES, params);
        });

        /**
         * ******************************************************
         */
        btnImp.addPopupItem("قـائـمـة زبائن الشركة", e -> {

            if (tab.getSelectedRow() == -1) {
                exite.showMessage("تنبيه", "الرجاء اختيار الشركة");
                return;
            }
            int row = tab.getSelectedRow();
            int id = (int) tab.getModel().getValueAt(row, 0);
            Entreprise entreprise = entrepriseDAOImpl.findById(id);
            params.put("ENTERPRISE_ID", entreprise.getId());
            if (!entreprise.getNom_ar().isEmpty()) {
                params.put("ENTERPRISE_NAME_FR", entreprise.getNom_ar());
            } else {
                params.put("ENTERPRISE_NAME_FR", entreprise.getNom_fr());
            }
            service_print.printReport(ReportNames.LIST_OF_CLIENT_BY_ID_ENTERPRISE, params);

        });
        /**
         * *******************************************************************
         */

    }

    public void setEntreprisesOnTab() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        List<Entreprise> entreprises = entrepriseDAOImpl.findAll();

        for (Entreprise entreprise : entreprises) {
            int id = entreprise.getId();
            String nom = entreprise.getNom_ar();
            String nom_fr = entreprise.getNom_fr();
            String adress = entreprise.getAdresse();
            String tel = entreprise.getTel();
            String des = entreprise.getDesc();
            String email = entreprise.getEmail();

            model.insertRow(0, new Object[]{id, tel, email, adress, des, nom_fr,
                nom});
//            model.addRow(new Object[]{id, tel, email, adress, des, nom_fr,
//                nom});
        }
        lab_nbVersement.setText(entreprises.size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        btnAdd = new material.design.buttonRounder();
        btnModf = new material.design.buttonRounder();
        btnSupprim = new material.design.buttonRounder();
        btnModf1 = new material.design.buttonRounder();
        btnImp = new material.design.buttonMenu();
        btnModf3 = new material.design.buttonRounder();
        jPanel1 = new javax.swing.JPanel();
        panRound4 = new ui.card.panRound();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_search = new material.design.SearchTextRound();
        panButtom = new javax.swing.JPanel();
        panRound1 = new ui.card.panRound();
        jLabel1 = new javax.swing.JLabel();
        lab_nbVersement = new javax.swing.JLabel();
        btnModf2 = new material.design.buttonRounder();
        buttonRounder1 = new material.design.buttonRounder();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panTop.setBackground(new java.awt.Color(255, 255, 255));
        panTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        panTop.setMinimumSize(new java.awt.Dimension(100, 50));
        panTop.setPreferredSize(new java.awt.Dimension(100, 50));

        btnAdd.setBackground(new java.awt.Color(22, 163, 74));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-plus-64 (2).png"))); // NOI18N
        btnAdd.setText("شركة جديدة");
        btnAdd.setActionCommand("");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAdd.setMaximumSize(new java.awt.Dimension(0, 74));
        btnAdd.setMinimumSize(new java.awt.Dimension(0, 74));
        btnAdd.setPreferredSize(new java.awt.Dimension(0, 74));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModf.setBackground(new java.awt.Color(112, 112, 193));
        btnModf.setForeground(new java.awt.Color(255, 255, 255));
        btnModf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-pencil-drawing-64.png"))); // NOI18N
        btnModf.setText("تعديــل ");
        btnModf.setActionCommand("");
        btnModf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActionPerformed(evt);
            }
        });

        btnSupprim.setBackground(new java.awt.Color(220, 0, 0));
        btnSupprim.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-trash-64.png"))); // NOI18N
        btnSupprim.setText("حذف ");
        btnSupprim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSupprim.setMaximumSize(new java.awt.Dimension(0, 74));
        btnSupprim.setMinimumSize(new java.awt.Dimension(0, 74));
        btnSupprim.setPreferredSize(new java.awt.Dimension(0, 74));
        btnSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimActionPerformed(evt);
            }
        });

        btnModf1.setBackground(new java.awt.Color(17, 152, 185));
        btnModf1.setForeground(new java.awt.Color(255, 255, 255));
        btnModf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/validation-du-billet (1).png"))); // NOI18N
        btnModf1.setText(" مدفوعات الـشـركــة   ");
        btnModf1.setActionCommand("");
        btnModf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf1.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf1.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf1.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf1ActionPerformed(evt);
            }
        });

        btnImp.setBackground(new java.awt.Color(51, 204, 255));
        btnImp.setForeground(new java.awt.Color(255, 255, 255));
        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-print-48.png"))); // NOI18N
        btnImp.setText("طــباعـة التـقـاريــر");
        btnImp.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpActionPerformed(evt);
            }
        });

        btnModf3.setBackground(new java.awt.Color(17, 152, 185));
        btnModf3.setForeground(new java.awt.Color(255, 255, 255));
        btnModf3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-search-64.png"))); // NOI18N
        btnModf3.setText("بحث");
        btnModf3.setActionCommand("");
        btnModf3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf3.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf3.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf3.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                    .addContainerGap(800, Short.MAX_VALUE)
                    .addComponent(btnModf3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(320, 320, 320)))
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
            .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(btnModf3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        add(panTop);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panRound4.setColor1(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        tab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tab.setForeground(new java.awt.Color(102, 102, 102));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "البريد الالكتروني", "الهاتف", "العنوان", "NIF", "اسم الشركة بالفرنسية", "الشركة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        txt_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panRound4Layout = new javax.swing.GroupLayout(panRound4);
        panRound4.setLayout(panRound4Layout);
        panRound4Layout.setHorizontalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(panRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRound4Layout.setVerticalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        add(jPanel1);

        panButtom.setBackground(new java.awt.Color(255, 255, 255));
        panButtom.setMaximumSize(new java.awt.Dimension(32767, 50));
        panButtom.setMinimumSize(new java.awt.Dimension(100, 50));

        panRound1.setBackground(new java.awt.Color(255, 255, 255));
        panRound1.setColor1(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("عــدد الشركات : ");

        lab_nbVersement.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lab_nbVersement.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_nbVersement.setText("00");

        javax.swing.GroupLayout panRound1Layout = new javax.swing.GroupLayout(panRound1);
        panRound1.setLayout(panRound1Layout);
        panRound1Layout.setHorizontalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_nbVersement, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );
        panRound1Layout.setVerticalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addGroup(panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_nbVersement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnModf2.setBackground(new java.awt.Color(51, 151, 151));
        btnModf2.setForeground(new java.awt.Color(255, 255, 255));
        btnModf2.setText("مـلـخـص مدفوعات الـشـركــات & الـديــون & الـمـبـيــعــات  ");
        btnModf2.setActionCommand("");
        btnModf2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf2.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf2.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf2.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf2ActionPerformed(evt);
            }
        });

        buttonRounder1.setBackground(new java.awt.Color(255, 153, 0));
        buttonRounder1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder1.setText("فـاتورة ديـون الشركة");
        buttonRounder1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        buttonRounder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panButtomLayout = new javax.swing.GroupLayout(panButtom);
        panButtom.setLayout(panButtomLayout);
        panButtomLayout.setHorizontalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtomLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(panRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnModf2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonRounder1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        panButtomLayout.setVerticalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModf2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRounder1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panButtom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddCompany(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Entreprise entreprise = entrepriseDAOImpl.findById(id);
            new ModifyCompany(this.homeForm, true, entreprise).setVisible(true);

        }
    }//GEN-LAST:event_btnModfActionPerformed

    private void btnSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Entreprise entreprise = entrepriseDAOImpl.findById(id);
            messageDialog.ShowConfirmMessageInFrame("تـأكـيد الـحــذف", "هـل أنت متـأكـد مـن عـمـلـية الـحــذف");
            if (messageDialog.getMessageType() == MessageDialog.MessageType.YES) {
                if (entrepriseDAOImpl.delete(id) > 0) {
                    setEntreprisesOnTab();
                    validationMessageDialog.showMessage("حـذف", "تم حذف الشركة بنجاح");
                } else {
                    new Exite(homeForm).showMessage("خــطـأ", "لا يمكنك حذف الشركة");
                }
            }
        }
    }//GEN-LAST:event_btnSupprimActionPerformed

    private void btnModf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf1ActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
             System.out.println("ID = " + id);
            Entreprise entreprise =  entrepriseDAOImpl.findById(id);
            new VersementEntrepriseForme(this.homeForm, true, entreprise).setVisible(true);
        }
                                       
    }//GEN-LAST:event_btnModf1ActionPerformed
    private int lastRow = -1;
    private void tabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseReleased
        if (!SwingUtilities.isLeftMouseButton(evt)) {
            return;
        }

        int row = tab.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tab.clearSelection();
            lastRow = -1;
            return;
        }

        if (lastRow == row) {
            tab.clearSelection();
            lastRow = -1;
        } else {
            tab.setRowSelectionInterval(row, row);
            lastRow = row;
        }
    }//GEN-LAST:event_tabMouseReleased

    private void buttonRounder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder1ActionPerformed
        if (tab.getSelectedRow() != -1) {
             int viewRow = tab.getSelectedRow();
    int row = tab.convertRowIndexToModel(viewRow);}
    }//GEN-LAST:event_buttonRounder1ActionPerformed

    private void btnImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpActionPerformed
        if (tab.getSelectedRow() != -1) {
             int viewRow = tab.getSelectedRow();
    int row = tab.convertRowIndexToModel(viewRow);}
    }//GEN-LAST:event_btnImpActionPerformed

    private void btnModf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf2ActionPerformed
              new AllVersementCreditVent(homeForm, true).setVisible(true);

    }//GEN-LAST:event_btnModf2ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
         lab_nbVersement.setText(tab.getRowCount()+"");
    }//GEN-LAST:event_txt_searchKeyReleased

    private void btnModf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModf3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnAdd;
    private material.design.buttonMenu btnImp;
    private material.design.buttonRounder btnModf;
    private material.design.buttonRounder btnModf1;
    private material.design.buttonRounder btnModf2;
    private material.design.buttonRounder btnModf3;
    private material.design.buttonRounder btnSupprim;
    private material.design.buttonRounder buttonRounder1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_nbVersement;
    private javax.swing.JPanel panButtom;
    private ui.card.panRound panRound1;
    private ui.card.panRound panRound4;
    private javax.swing.JPanel panTop;
    private javax.swing.JTable tab;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.SearchTextRound txt_search;
    // End of variables declaration//GEN-END:variables
}
