/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.ProduitDAOImpl;
import entity.Categorie;
import entity.Produit;
import frame.AddProduit;
import frame.ModifyProduit;
import frame.Nouvelle_Achat;
import home.HomeForm;
import java.sql.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import material.design.designeTable;

/**
 *
 * @author pc
 */
public class pan_produit extends javax.swing.JPanel {

    HomeForm homeForm;
    Connection connection;
    ProduitDAOImpl produitDAOImpl;
    ValidationMessageDialog validationMessageDialog;
    Exite exite;
    MessageDialog messageDialog;

    public pan_produit(HomeForm homeForm) {
        this.homeForm = homeForm;
        initComponents();

        validationMessageDialog = new ValidationMessageDialog(homeForm);
        exite = new Exite(homeForm);
        messageDialog = new MessageDialog(homeForm);

        connection = DatabaseConnection.getInstance().getConnection();
        produitDAOImpl = new ProduitDAOImpl(connection);

        new designeTable().SearchTable(tab, txt_search);
        new designeTable().setDesignTable(tab, jScrollPane2);
        setProduitsOnTab();

        TableColumn column = tab.getColumnModel().getColumn(0);
        tab.getColumnModel().removeColumn(column);

    }

    public void setProduitsOnTab() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        List<Produit> produits = produitDAOImpl.findAll();
        String marque = "";
        for (Produit produit : produits) {
            int id = produit.getId();
            String refernce = produit.getReference();
            String desg = produit.getDesignation();
            Categorie categorie = produit.getCategorie();

            if (categorie != null) {
                marque = categorie.getNomCategorie();
            }
            double prix_ache = produit.getPrix_achat();
            double prix_vent = produit.getPrix_vente();
            int qt = produit.getQty();

            model.addRow(new Object[]{id, prix_vent, prix_ache, qt, refernce, marque,
                marque, desg});
        }

        lab_nbProduit.setText(produits.size() + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        btnModf = new material.design.buttonRounder();
        btnAdd = new material.design.buttonRounder();
        btnSupprim = new material.design.buttonRounder();
        btnModf1 = new material.design.buttonRounder();
        btnNewAchat = new material.design.buttonRounder();
        panCenter = new javax.swing.JPanel();
        panRound1 = new ui.card.panRound();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_search = new material.design.SearchTextRound();
        panRound2 = new ui.card.panRound();
        jLabel = new javax.swing.JLabel();
        lab_nbProduit = new javax.swing.JLabel();
        panbuttom = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        panTop.setBackground(new java.awt.Color(255, 255, 255));
        panTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        panTop.setMinimumSize(new java.awt.Dimension(200, 50));
        panTop.setPreferredSize(new java.awt.Dimension(300, 50));

        btnModf.setBackground(new java.awt.Color(204, 0, 204));
        btnModf.setForeground(new java.awt.Color(255, 255, 255));
        btnModf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-pencil-drawing-64.png"))); // NOI18N
        btnModf.setText("تعديل منتج");
        btnModf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf.setPreferredSize(new java.awt.Dimension(130, 70));
        btnModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(22, 163, 74));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-plus-64 (2).png"))); // NOI18N
        btnAdd.setText("منتج جديد");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAdd.setPreferredSize(new java.awt.Dimension(130, 70));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSupprim.setBackground(new java.awt.Color(220, 0, 0));
        btnSupprim.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-trash-64.png"))); // NOI18N
        btnSupprim.setText("حذف منتج");
        btnSupprim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSupprim.setPreferredSize(new java.awt.Dimension(130, 70));
        btnSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimActionPerformed(evt);
            }
        });

        btnModf1.setBackground(new java.awt.Color(17, 152, 185));
        btnModf1.setForeground(new java.awt.Color(255, 255, 255));
        btnModf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-search-64.png"))); // NOI18N
        btnModf1.setText("بحث");
        btnModf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf1ActionPerformed(evt);
            }
        });

        btnNewAchat.setBackground(new java.awt.Color(51, 51, 51));
        btnNewAchat.setForeground(new java.awt.Color(255, 255, 255));
        btnNewAchat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-panier-rapide-30.png"))); // NOI18N
        btnNewAchat.setText("طلبية شراء");
        btnNewAchat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnNewAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAchatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnNewAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSupprim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(panTop);

        panCenter.setBackground(new java.awt.Color(255, 255, 255));

        panRound1.setColor1(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        tab.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tab.setForeground(new java.awt.Color(102, 102, 102));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "سعر البيع", "سعر الشراء", "العدد", "ref", "النوع", "العلامة التجارية ", "اسم المنتج/desig"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panRound1Layout = new javax.swing.GroupLayout(panRound1);
        panRound1.setLayout(panRound1Layout);
        panRound1Layout.setHorizontalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRound1Layout.setVerticalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panRound2.setBackground(new java.awt.Color(255, 255, 255));
        panRound2.setColor1(new java.awt.Color(255, 255, 255));

        jLabel.setFont(new java.awt.Font("Cairo", 1, 13)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 204, 0));
        jLabel.setText("عــدد المنتجات : ");

        lab_nbProduit.setFont(new java.awt.Font("Cairo", 1, 13)); // NOI18N
        lab_nbProduit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_nbProduit.setText("00");

        javax.swing.GroupLayout panRound2Layout = new javax.swing.GroupLayout(panRound2);
        panRound2.setLayout(panRound2Layout);
        panRound2Layout.setHorizontalGroup(
            panRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_nbProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        panRound2Layout.setVerticalGroup(
            panRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound2Layout.createSequentialGroup()
                .addGroup(panRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lab_nbProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout panCenterLayout = new javax.swing.GroupLayout(panCenter);
        panCenter.setLayout(panCenterLayout);
        panCenterLayout.setHorizontalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCenterLayout.createSequentialGroup()
                        .addComponent(panRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panCenterLayout.createSequentialGroup()
                        .addComponent(panRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        panCenterLayout.setVerticalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(panCenter);

        panbuttom.setBackground(new java.awt.Color(255, 255, 255));
        panbuttom.setMaximumSize(new java.awt.Dimension(32767, 50));
        panbuttom.setMinimumSize(new java.awt.Dimension(200, 50));
        panbuttom.setName(""); // NOI18N
        panbuttom.setPreferredSize(new java.awt.Dimension(169, 50));

        javax.swing.GroupLayout panbuttomLayout = new javax.swing.GroupLayout(panbuttom);
        panbuttom.setLayout(panbuttomLayout);
        panbuttomLayout.setHorizontalGroup(
            panbuttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panbuttomLayout.setVerticalGroup(
            panbuttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(panbuttom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddProduit(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimActionPerformed
        if (tab.getSelectedRow() != -1) {
            int row = tab.getSelectedRow();
            int id = (int) tab.getModel().getValueAt(row, 0);
            Produit produit = produitDAOImpl.findById(id);
            messageDialog.ShowConfirmMessageInFrame("تـأكـيد الـحـذف", "هـل أنت متـأكـد مـن حـذف الـنـوعـيـة");
            if (messageDialog.getMessageType() == MessageDialog.MessageType.YES  ) {
                if (produitDAOImpl.delete(id) > 0) {
                    validationMessageDialog.showMessage("خــطـأ", "تم حذف المنتج بنجاح");
                    setProduitsOnTab();
                }else {
                exite.showMessage("خــطـأ", "لا يمكنك الحذف  قـم بـتـحـديـد الـمـنـتـج");
            }
            } 
        }
    }//GEN-LAST:event_btnSupprimActionPerformed

    private void btnModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActionPerformed
        if (tab.getSelectedRow() != -1) {
            int row = tab.getSelectedRow();
            int id = (int) tab.getModel().getValueAt(row, 0);
            Produit produit = produitDAOImpl.findById(id);
            new ModifyProduit(this.homeForm, true, produit).setVisible(true);

        }

    }//GEN-LAST:event_btnModfActionPerformed

    private void btnModf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf1ActionPerformed
        txt_search.requestFocus();
    }//GEN-LAST:event_btnModf1ActionPerformed

    private void btnNewAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAchatActionPerformed
        new Nouvelle_Achat(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnNewAchatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnAdd;
    private material.design.buttonRounder btnModf;
    private material.design.buttonRounder btnModf1;
    private material.design.buttonRounder btnNewAchat;
    private material.design.buttonRounder btnSupprim;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_nbProduit;
    private javax.swing.JPanel panCenter;
    private ui.card.panRound panRound1;
    private ui.card.panRound panRound2;
    private javax.swing.JPanel panTop;
    private javax.swing.JPanel panbuttom;
    private javax.swing.JTable tab;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.SearchTextRound txt_search;
    // End of variables declaration//GEN-END:variables
}
