/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.CategorieDAOImpl;
import entity.Categorie;
import frame.AddCategory;
import frame.ModifyCategory;
import home.HomeForm;
import java.sql.Connection;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import material.design.designeTable;

/**
 *
 * @author pc
 */
public class pan_categorie extends javax.swing.JPanel {

    HomeForm homeForm;
    Connection connection;
    CategorieDAOImpl categorieDAOImpl;
    MessageDialog messageDialog;

    public pan_categorie(HomeForm homeForm) {
        this.homeForm = homeForm;
        initComponents();
        connection = DatabaseConnection.getInstance().getConnection();
        categorieDAOImpl = new CategorieDAOImpl(connection);
        messageDialog = new MessageDialog(homeForm);
        new designeTable().SearchTable(tab, txt_search);
        new designeTable().setDesignTable(tab, jScrollPane2);

        TableColumn column = tab.getColumnModel().getColumn(0);
        tab.getColumnModel().removeColumn(column);

        setCategoriesOnTab();

    }

    public void setCategoriesOnTab() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        List<Categorie> categories = categorieDAOImpl.findAll();
        for (Categorie categorie : categories) {
            int id = categorie.getId();
            String nom_ar = categorie.getNomCategorie();
            String nom_fr = categorie.getDescription();
            model.insertRow(0, new Object[]{id, nom_fr, nom_ar});
            //   model.addRow(new Object[]{id,  nom_fr, nom_ar});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        btnSupprim = new material.design.buttonRounder();
        btnModf = new material.design.buttonRounder();
        btnAdd = new material.design.buttonRounder();
        btnModf1 = new material.design.buttonRounder();
        panCenter = new javax.swing.JPanel();
        panRound4 = new ui.card.panRound();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_search = new material.design.SearchTextRound();
        panButtom = new javax.swing.JPanel();
        panRound2 = new ui.card.panRound();
        jLabel = new javax.swing.JLabel();
        lab_nbCatego = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        panTop.setBackground(new java.awt.Color(255, 255, 255));
        panTop.setMinimumSize(new java.awt.Dimension(100, 50));
        panTop.setPreferredSize(new java.awt.Dimension(242, 50));

        btnSupprim.setBackground(new java.awt.Color(220, 0, 0));
        btnSupprim.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-trash-64.png"))); // NOI18N
        btnSupprim.setText("حذف ");
        btnSupprim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimActionPerformed(evt);
            }
        });

        btnModf.setBackground(new java.awt.Color(204, 0, 204));
        btnModf.setForeground(new java.awt.Color(255, 255, 255));
        btnModf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-pencil-drawing-64.png"))); // NOI18N
        btnModf.setText("تعديل النوعية ");
        btnModf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(22, 163, 74));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-plus-64 (2).png"))); // NOI18N
        btnAdd.setText("نوعية جديدة");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModf1.setBackground(new java.awt.Color(17, 152, 185));
        btnModf1.setForeground(new java.awt.Color(255, 255, 255));
        btnModf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-search-64.png"))); // NOI18N
        btnModf1.setText("بحث");
        btnModf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        add(panTop);

        panCenter.setBackground(new java.awt.Color(255, 255, 255));

        panRound4.setColor1(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        tab.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        tab.setForeground(new java.awt.Color(102, 102, 102));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "النوعية بالفرنسية", "النوعية"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        txt_search.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panRound4Layout = new javax.swing.GroupLayout(panRound4);
        panRound4.setLayout(panRound4Layout);
        panRound4Layout.setHorizontalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRound4Layout.setVerticalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panCenterLayout = new javax.swing.GroupLayout(panCenter);
        panCenter.setLayout(panCenterLayout);
        panCenterLayout.setHorizontalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        panCenterLayout.setVerticalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(panCenter);

        panButtom.setBackground(new java.awt.Color(255, 255, 255));
        panButtom.setMaximumSize(new java.awt.Dimension(32767, 50));
        panButtom.setMinimumSize(new java.awt.Dimension(100, 50));
        panButtom.setPreferredSize(new java.awt.Dimension(242, 50));

        panRound2.setBackground(new java.awt.Color(255, 255, 255));
        panRound2.setColor1(new java.awt.Color(255, 255, 255));

        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 204, 0));
        jLabel.setText("العدد");

        lab_nbCatego.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lab_nbCatego.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_nbCatego.setText("00");

        javax.swing.GroupLayout panRound2Layout = new javax.swing.GroupLayout(panRound2);
        panRound2.setLayout(panRound2Layout);
        panRound2Layout.setHorizontalGroup(
            panRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_nbCatego, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panRound2Layout.setVerticalGroup(
            panRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound2Layout.createSequentialGroup()
                .addComponent(lab_nbCatego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panRound2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panButtomLayout = new javax.swing.GroupLayout(panButtom);
        panButtom.setLayout(panButtomLayout);
        panButtomLayout.setHorizontalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtomLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(panRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(748, Short.MAX_VALUE))
        );
        panButtomLayout.setVerticalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(panButtom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddCategory(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Categorie categorie = categorieDAOImpl.findById(id);
            messageDialog.ShowConfirmMessageInFrame("تـأكـيد الـحـذف", "هـل أنت متـأكـد مـن حـذف الـنـوعـيـة");
            if (messageDialog.getMessageType() == MessageDialog.MessageType.YES) {
                if (categorieDAOImpl.delete(id) > 0) {
                    setCategoriesOnTab();
                    new ValidationMessageDialog(homeForm).showMessage("حـذف", "تم حذف الـنـوعـيـة بنجاح");
                } else {
                    new Exite(homeForm).showMessage("خــطـأ", "لا يمكنك حذف الـنـوعـية");
                }
            }
        }
    }//GEN-LAST:event_btnSupprimActionPerformed

    private void btnModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Categorie categorie = categorieDAOImpl.findById(id);
            new ModifyCategory(this.homeForm, true, categorie).setVisible(true);

        }

    }//GEN-LAST:event_btnModfActionPerformed

    private void btnModf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf1ActionPerformed
        txt_search.requestFocus();
    }//GEN-LAST:event_btnModf1ActionPerformed
    private int lastRow = -1;
    private void tabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseReleased
        if (!SwingUtilities.isLeftMouseButton(evt)) {
            return;
        }

        int row = tab.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tab.clearSelection();
            lastRow = -1;
            return;
        }

        if (lastRow == row) {
            tab.clearSelection();
            lastRow = -1;
        } else {
            tab.setRowSelectionInterval(row, row);
            lastRow = row;
        }
    }//GEN-LAST:event_tabMouseReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
    }//GEN-LAST:event_txt_searchKeyPressed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        lab_nbCatego.setText(tab.getRowCount() + "");
    }//GEN-LAST:event_txt_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnAdd;
    private material.design.buttonRounder btnModf;
    private material.design.buttonRounder btnModf1;
    private material.design.buttonRounder btnSupprim;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_nbCatego;
    private javax.swing.JPanel panButtom;
    private javax.swing.JPanel panCenter;
    private ui.card.panRound panRound2;
    private ui.card.panRound panRound4;
    private javax.swing.JPanel panTop;
    private javax.swing.JTable tab;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.SearchTextRound txt_search;
    // End of variables declaration//GEN-END:variables
}
