/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import Reports.PrintingService;
import Reports.ReportNames;
import config.DatabaseConnection;
import dao.impl.EntrepriseDAOImpl;
import entity.Client;
import entity.Entreprise;
import frame.AddCompany;
import frame.ModifyCompany;
import home.HomeForm;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import material.design.designeTable;

public class pan_Entreprise extends javax.swing.JPanel {

    HomeForm homeForm;
    Connection connection;
    EntrepriseDAOImpl entrepriseDAOImpl;
    PrintingService service_print = new PrintingService();
    Map<String, Object> params = new HashMap<>();
  ValidationMessageDialog   validationMessageDialog;
  MessageDialog messageDialog;
  Exite exite;
    public pan_Entreprise(HomeForm homeForm) {
        this.homeForm = homeForm;
        initComponents();
        connection = DatabaseConnection.getInstance().getConnection();
        entrepriseDAOImpl = new EntrepriseDAOImpl(connection);
        validationMessageDialog= new ValidationMessageDialog(homeForm);
        exite= new Exite(homeForm);
        messageDialog= new MessageDialog(homeForm);
        
        new designeTable().SearchTable(tab, txt_search);
        new designeTable().setDesignTable(tab, jScrollPane2);
        TableColumn column = tab.getColumnModel().getColumn(0);
        tab.getColumnModel().removeColumn(column);
        
        setEntreprisesOnTab();

        print();

    }

    private void print() {
        btnImp.addPopupItem("قـائـمـة  الـشـركـات", e -> {
            //ListEnterprises
        service_print.printReport(ReportNames.LIST_ENTERPRISES, null);
        });
        
        btnImp.addPopupItem("قـائـمـة مـدفـوعـات كل الـشـركـات", e -> {
            params = new HashMap<>();
            //ALL_VERSEMENT_ENTERPRISES
            service_print.printReport(ReportNames.ALL_VERSEMENT_ENTERPRISES, null);
        });
        
/*********************************************************/
        btnImp.addPopupItem("قـائـمـة زبائن الشركة", e -> {
            
            if (tab.getSelectedRow() == -1){
             exite.showMessage("تنبيه", "الرجاء اختيار الشركة");
             return;
            } 
                int row = tab.getSelectedRow();
                int id = (int) tab.getModel().getValueAt(row, 0);
                Entreprise entreprise = entrepriseDAOImpl.findById(id);
                params.put("ENTERPRISE_ID", entreprise.getId());
                if (!entreprise.getNom_fr().isEmpty()) {
                    params.put("ENTERPRISE_NAME_FR", entreprise.getNom_fr());
                } else {
                    params.put("ENTERPRISE_NAME_FR", entreprise.getNom_ar());
                }
                service_print.printReport(ReportNames.LIST_OF_CLIENT_BY_ID_ENTERPRISE, params);
            
        });
        /**********************************************************************/
        
        
    }

    public void setEntreprisesOnTab() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        List<Entreprise> entreprises = entrepriseDAOImpl.findAll();

        for (Entreprise entreprise : entreprises) {
            int id = entreprise.getId();
            String nom = entreprise.getNom_ar();
            String nom_fr = entreprise.getNom_fr();
            String adress = entreprise.getAdresse();
            String tel = entreprise.getTel();
            String des = entreprise.getDesc();
            String email = entreprise.getEmail();

            model.addRow(new Object[]{id, tel, email, adress, des, nom_fr,
                nom});
        }
        lab_nbClient.setText(entreprises.size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        btnAdd = new material.design.buttonRounder();
        btnModf = new material.design.buttonRounder();
        btnSupprim = new material.design.buttonRounder();
        btnModf1 = new material.design.buttonRounder();
        btnImp = new material.design.buttonMenu();
        jPanel1 = new javax.swing.JPanel();
        panRound4 = new ui.card.panRound();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_search = new material.design.SearchTextRound();
        panRound1 = new ui.card.panRound();
        jLabel1 = new javax.swing.JLabel();
        lab_nbClient = new javax.swing.JLabel();
        panButtom = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panTop.setBackground(new java.awt.Color(255, 255, 255));
        panTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        panTop.setMinimumSize(new java.awt.Dimension(100, 50));
        panTop.setPreferredSize(new java.awt.Dimension(100, 50));

        btnAdd.setBackground(new java.awt.Color(22, 163, 74));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-plus-64 (2).png"))); // NOI18N
        btnAdd.setText("شركة جديدة");
        btnAdd.setActionCommand("");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAdd.setMaximumSize(new java.awt.Dimension(0, 74));
        btnAdd.setMinimumSize(new java.awt.Dimension(0, 74));
        btnAdd.setPreferredSize(new java.awt.Dimension(0, 74));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModf.setBackground(new java.awt.Color(112, 112, 193));
        btnModf.setForeground(new java.awt.Color(255, 255, 255));
        btnModf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-pencil-drawing-64.png"))); // NOI18N
        btnModf.setText("تعديــل ");
        btnModf.setActionCommand("");
        btnModf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActionPerformed(evt);
            }
        });

        btnSupprim.setBackground(new java.awt.Color(220, 0, 0));
        btnSupprim.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-trash-64.png"))); // NOI18N
        btnSupprim.setText("حذف ");
        btnSupprim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSupprim.setMaximumSize(new java.awt.Dimension(0, 74));
        btnSupprim.setMinimumSize(new java.awt.Dimension(0, 74));
        btnSupprim.setPreferredSize(new java.awt.Dimension(0, 74));
        btnSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimActionPerformed(evt);
            }
        });

        btnModf1.setBackground(new java.awt.Color(17, 152, 185));
        btnModf1.setForeground(new java.awt.Color(255, 255, 255));
        btnModf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-search-64.png"))); // NOI18N
        btnModf1.setText("بحث");
        btnModf1.setActionCommand("");
        btnModf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf1.setMaximumSize(new java.awt.Dimension(0, 74));
        btnModf1.setMinimumSize(new java.awt.Dimension(0, 74));
        btnModf1.setPreferredSize(new java.awt.Dimension(0, 74));
        btnModf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf1ActionPerformed(evt);
            }
        });

        btnImp.setBackground(new java.awt.Color(51, 204, 255));
        btnImp.setForeground(new java.awt.Color(255, 255, 255));
        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-print-48.png"))); // NOI18N
        btnImp.setText("طــباعـة التـقـاريــر");
        btnImp.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(panTop);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panRound4.setColor1(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        tab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tab.setForeground(new java.awt.Color(102, 102, 102));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "البريد الالكتروني", "الهاتف", "العنوان", "Des", " entreprise", "الشركة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panRound4Layout = new javax.swing.GroupLayout(panRound4);
        panRound4.setLayout(panRound4Layout);
        panRound4Layout.setHorizontalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(panRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRound4Layout.setVerticalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panRound1.setBackground(new java.awt.Color(255, 255, 255));
        panRound1.setColor1(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("عــدد الشركات : ");

        lab_nbClient.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        lab_nbClient.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_nbClient.setText("00");

        javax.swing.GroupLayout panRound1Layout = new javax.swing.GroupLayout(panRound1);
        panRound1.setLayout(panRound1Layout);
        panRound1Layout.setHorizontalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_nbClient, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        panRound1Layout.setVerticalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound1Layout.createSequentialGroup()
                .addGroup(panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRound1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(lab_nbClient))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1);

        panButtom.setBackground(new java.awt.Color(255, 255, 255));
        panButtom.setMaximumSize(new java.awt.Dimension(32767, 50));
        panButtom.setMinimumSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout panButtomLayout = new javax.swing.GroupLayout(panButtom);
        panButtom.setLayout(panButtomLayout);
        panButtomLayout.setHorizontalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1241, Short.MAX_VALUE)
        );
        panButtomLayout.setVerticalGroup(
            panButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(panButtom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddCompany(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActionPerformed
        if (tab.getSelectedRow() != -1) {
            int row = tab.getSelectedRow();
            int id = (int) tab.getModel().getValueAt(row, 0);
            Entreprise entreprise = entrepriseDAOImpl.findById(id);
            new ModifyCompany(this.homeForm, true, entreprise).setVisible(true);

        }
    }//GEN-LAST:event_btnModfActionPerformed

    private void btnSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimActionPerformed
        if (tab.getSelectedRow() != -1) {
            int row = tab.getSelectedRow();
            int id = (int) tab.getModel().getValueAt(row, 0);
            Entreprise entreprise = entrepriseDAOImpl.findById(id);
            messageDialog.ShowConfirmMessageInFrame("تـأكـيد الـحــذف", "هـل أنت متـأكـد مـن عـمـلـية الـحــذف");
            if (messageDialog.getMessageType() == MessageDialog.MessageType.YES) {
            if (entrepriseDAOImpl.delete(id) > 0) {
                setEntreprisesOnTab();
               validationMessageDialog.showMessage("حـذف", "تم حذف الشركة بنجاح");
            } else {
                new Exite(homeForm).showMessage("خــطـأ", "لا يمكنك حذف الشركة");
            }
            }
        }
    }//GEN-LAST:event_btnSupprimActionPerformed

    private void btnModf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf1ActionPerformed
        txt_search.requestFocusInWindow();
        txt_search.selectAll();
    }//GEN-LAST:event_btnModf1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnAdd;
    private material.design.buttonMenu btnImp;
    private material.design.buttonRounder btnModf;
    private material.design.buttonRounder btnModf1;
    private material.design.buttonRounder btnSupprim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_nbClient;
    private javax.swing.JPanel panButtom;
    private ui.card.panRound panRound1;
    private ui.card.panRound panRound4;
    private javax.swing.JPanel panTop;
    private javax.swing.JTable tab;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.SearchTextRound txt_search;
    // End of variables declaration//GEN-END:variables
}
