/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import Reports.PrintingService;
import Reports.ReportNames;
import config.DatabaseConnection;
import dao.impl.ClientDAOImpl;
import entity.ArchiveSuppression;
import entity.Client;
import frame.AddClient;
import frame.ModifyClient;
import home.HomeForm;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import material.design.designeTable;

/**
 *
 * @author pc
 */
public class PanClient extends javax.swing.JPanel {

    HomeForm homeForm;
    Connection connection;
    ClientDAOImpl clientDAOImpl;
    MessageDialog messageDialog;
    Exite exite;

    public PanClient(HomeForm homeForm) {
        this.homeForm = homeForm;
        initComponents();
        connection = DatabaseConnection.getInstance().getConnection();
        clientDAOImpl = new ClientDAOImpl(connection);
        messageDialog = new MessageDialog(homeForm);
        exite = new Exite(homeForm);

        new designeTable().SearchTable(tab, txt_search);
        new designeTable().setDesignTable(tab, jScrollPane2);

        TableColumn column = tab.getColumnModel().getColumn(0);
        tab.getColumnModel().removeColumn(column);

        setClientsOnTab();
        print();

    }

    public void print() {
        PrintingService service_print = new PrintingService();
        Map<String, Object> params1 = new HashMap<>();
        btnImp.addPopupItem("قـائـمـة الـزبـائـن", e -> {
//            Client client = clientDAOImpl.findById(5);
//            params1.put("CLIENT_ID", client.getId());
//            params1.put("FName", client.getNom());
//            if (!client.getEntreprise().getNom_ar().isEmpty()) {
//                params1.put("ENTERPRISE_NAME_FR", client.getEntreprise().getNom_ar());
//            } else {
//                params1.put("ENTERPRISE_NAME_FR", client.getEntreprise().getNom_fr());
//            }

            service_print.printReport(ReportNames.CLIENT_LIST, params1);

        });
        
        btnImp.addPopupItem("قـائــمـة مـشـتـريـات الزبـون", e -> {
            if (tab.getSelectedRow() != -1) {
               Map<String, Object> params = new HashMap<>();
                 int viewRow = tab.getSelectedRow();
                 int row = tab.convertRowIndexToModel(viewRow);
                 
                int id = (int) tab.getModel().getValueAt(row, 0);
                Client client = clientDAOImpl.findById(id);
                params.put("CLIENT_ID", client.getId());
                params.put("FName", client.getNom() + " " + client.getPrenom());
                if (!client.getEntreprise().getNom_ar().isEmpty()) {
                    params.put("ENTERPRISE_NAME_FR", client.getEntreprise().getNom_ar());
                } else {
                    params.put("ENTERPRISE_NAME_FR", client.getEntreprise().getNom_fr());
                }

                service_print.printReport(ReportNames.CLIENT_PURCHASES_BY_ID, params);

            } else {
                exite.showMessage("خـطـأ", "قـم بـتـحـديـد الــزبـون مـن الـجـدول");

            }
        });

    }

    public void setClientsOnTab() {
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        List<Client> clients = clientDAOImpl.findAll();
        String nom_entreprise = "";
        for (Client client : clients) {
            String matricul = client.getMatricule();
            int id = client.getId();
            String nom = client.getNom();
            String prenom = client.getPrenom();
            String adress = client.getAdresse();
            String tel = client.getTel();
            nom_entreprise = "/";
            System.out.println("size  : " + clients.size());
            System.out.println("size  : " + clients.toString());
            if (client.getEntreprise() != null) {
                nom_entreprise = client.getEntreprise().getNom_ar();
            }
            model.insertRow(0, new Object[]{id, tel, adress, nom_entreprise, prenom
                + " " + nom, matricul});
//            model.addRow(new Object[]{id, tel, adress, nom_entreprise, prenom
//                + " " + nom});
        }
        lab_nbClient.setText(clients.size() + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTop = new javax.swing.JPanel();
        btnSupprim = new material.design.buttonRounder();
        btnModf1 = new material.design.buttonRounder();
        btnModf = new material.design.buttonRounder();
        btnAdd = new material.design.buttonRounder();
        btnImp = new material.design.buttonMenu();
        panCenter = new javax.swing.JPanel();
        panRound4 = new ui.card.panRound();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_search = new material.design.SearchTextRound();
        panbuttom = new javax.swing.JPanel();
        panRound1 = new ui.card.panRound();
        jLabel1 = new javax.swing.JLabel();
        lab_nbClient = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        panTop.setBackground(new java.awt.Color(255, 255, 255));
        panTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        panTop.setMinimumSize(new java.awt.Dimension(50, 50));
        panTop.setPreferredSize(new java.awt.Dimension(0, 50));

        btnSupprim.setBackground(new java.awt.Color(220, 0, 0));
        btnSupprim.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-trash-64.png"))); // NOI18N
        btnSupprim.setText("حذف ");
        btnSupprim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSupprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimActionPerformed(evt);
            }
        });

        btnModf1.setBackground(new java.awt.Color(17, 152, 185));
        btnModf1.setForeground(new java.awt.Color(255, 255, 255));
        btnModf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-search-64.png"))); // NOI18N
        btnModf1.setText("بحث");
        btnModf1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModf1ActionPerformed(evt);
            }
        });

        btnModf.setBackground(new java.awt.Color(112, 112, 193));
        btnModf.setForeground(new java.awt.Color(255, 255, 255));
        btnModf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-pencil-drawing-64.png"))); // NOI18N
        btnModf.setText("تعديل ");
        btnModf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModfActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(22, 163, 74));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-plus-64 (2).png"))); // NOI18N
        btnAdd.setText("زبون جديد");
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnImp.setBackground(new java.awt.Color(51, 204, 255));
        btnImp.setForeground(new java.awt.Color(255, 255, 255));
        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-print-48.png"))); // NOI18N
        btnImp.setText("طــباعـة التـقـاريــر");
        btnImp.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        javax.swing.GroupLayout panTopLayout = new javax.swing.GroupLayout(panTop);
        panTop.setLayout(panTopLayout);
        panTopLayout.setHorizontalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panTopLayout.setVerticalGroup(
            panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSupprim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panTop);

        panCenter.setBackground(new java.awt.Color(255, 255, 255));

        panRound4.setColor1(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        tab.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        tab.setForeground(new java.awt.Color(102, 102, 102));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "الهاتف", "العنوان", "الشركة ", "الاسم و اللقب", "رقم التعريف الوظيفي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        txt_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panRound4Layout = new javax.swing.GroupLayout(panRound4);
        panRound4.setLayout(panRound4Layout);
        panRound4Layout.setHorizontalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRound4Layout.setVerticalGroup(
            panRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout panCenterLayout = new javax.swing.GroupLayout(panCenter);
        panCenter.setLayout(panCenterLayout);
        panCenterLayout.setHorizontalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        panCenterLayout.setVerticalGroup(
            panCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panCenter);

        panbuttom.setBackground(new java.awt.Color(255, 255, 255));
        panbuttom.setMaximumSize(new java.awt.Dimension(32767, 50));
        panbuttom.setMinimumSize(new java.awt.Dimension(50, 50));
        panbuttom.setPreferredSize(new java.awt.Dimension(0, 50));

        panRound1.setBackground(new java.awt.Color(255, 255, 255));
        panRound1.setColor1(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("عــدد الزبــائــن : ");

        lab_nbClient.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lab_nbClient.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_nbClient.setText("00");

        javax.swing.GroupLayout panRound1Layout = new javax.swing.GroupLayout(panRound1);
        panRound1.setLayout(panRound1Layout);
        panRound1Layout.setHorizontalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_nbClient, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        panRound1Layout.setVerticalGroup(
            panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRound1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_nbClient, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panbuttomLayout = new javax.swing.GroupLayout(panbuttom);
        panbuttom.setLayout(panbuttomLayout);
        panbuttomLayout.setHorizontalGroup(
            panbuttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbuttomLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(panRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        panbuttomLayout.setVerticalGroup(
            panbuttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panbuttom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddClient(this.homeForm, true).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSupprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Client client = clientDAOImpl.findById(id);

            messageDialog.ShowConfirmMessageInFrame("تـأكـيد الحـذف", "هـل أنت متـأكـد مـن حـذف المـنتـج");

            if (messageDialog.getMessageType() == MessageDialog.MessageType.YES) {
                if (clientDAOImpl.delete(id) > 0) {
                    new ArchiveSuppression().archiver(client);
                    new ValidationMessageDialog(homeForm).showMessage("حـذف", "تم حذف المنتج بنجاح");
                    setClientsOnTab();

                } else {
                    new Exite(homeForm).showMessage("خــطـأ", "لا يمكنك حذف المنتج");
                }
            }
        }
    }//GEN-LAST:event_btnSupprimActionPerformed

    private void btnModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModfActionPerformed
        if (tab.getSelectedRow() != -1) {
            int viewRow = tab.getSelectedRow();
            int row = tab.convertRowIndexToModel(viewRow);
            int id = (int) tab.getModel().getValueAt(row, 0);
            Client client = clientDAOImpl.findById(id);
            new ModifyClient(this.homeForm, true, client).setVisible(true);
        }


    }//GEN-LAST:event_btnModfActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btnModf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModf1ActionPerformed
        txt_search.requestFocusInWindow();
        txt_search.selectAll();
    }//GEN-LAST:event_btnModf1ActionPerformed
    private int lastRow = -1;
    private void tabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseReleased
        if (!SwingUtilities.isLeftMouseButton(evt)) {
            return;
        }

        int row = tab.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tab.clearSelection();
            lastRow = -1;
            return;
        }

        if (lastRow == row) {
            tab.clearSelection();
            lastRow = -1;
        } else {
            tab.setRowSelectionInterval(row, row);
            lastRow = row;
        }
    }//GEN-LAST:event_tabMouseReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        lab_nbClient.setText(tab.getRowCount()+"");
    }//GEN-LAST:event_txt_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnAdd;
    private material.design.buttonMenu btnImp;
    private material.design.buttonRounder btnModf;
    private material.design.buttonRounder btnModf1;
    private material.design.buttonRounder btnSupprim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab_nbClient;
    private javax.swing.JPanel panCenter;
    private ui.card.panRound panRound1;
    private ui.card.panRound panRound4;
    private javax.swing.JPanel panTop;
    private javax.swing.JPanel panbuttom;
    private javax.swing.JTable tab;
    private ui.table.TableScrollButton tableScrollButton1;
    private material.design.SearchTextRound txt_search;
    // End of variables declaration//GEN-END:variables
}
