/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JComponent;
import javax.swing.JPanel;
import material.design.button;

/**
 *
 * @author pc
 */
public class PanProduitCategorie extends javax.swing.JPanel {

    pan_produit pan_produit;
    pan_categorie pan_categorie;
    public PanProduitCategorie(pan_produit pan_produit,pan_categorie pan_categorie) {
        initComponents();
        this.pan_produit=pan_produit;
        this.pan_categorie = pan_categorie;
        setForm(pan_produit);
    }
    
    
    private void setForm( JComponent com) {
//        pan_centre.removeAll();
//        pan_centre.add(com);
//        pan_centre.repaint();
//        pan_centre.revalidate();
pan_centre.removeAll();
    
    pan_centre.setLayout(new java.awt.BorderLayout()); 
    pan_centre.add(com, java.awt.BorderLayout.CENTER);
    
    // تحديث وإعادة رسم اللوحة بشكل آمن ومضمون
    pan_centre.revalidate();
    pan_centre.repaint();
    }

    private void setMenu(JPanel pan, button btn) {
        for (Component component : pan.getComponents()) {
            if (component instanceof button) {
                button button = (button) component;
                button.setColor1(new Color(156, 156, 255));
                button.setColor2(new Color(156, 156, 255));
                // button.repaint();
                // button.revalidate();
            }
        }
        btn.setColor2(Color.WHITE);
        btn.setColor1(new Color(0, 204, 204));
        //  btn.setColor1(new Color(0,204,204));
        pan.repaint();
        pan.revalidate();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_menu = new javax.swing.JPanel();
        btn_catego = new material.design.button();
        btn_produit = new material.design.button();
        pan_centre = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pan_menu.setBackground(new java.awt.Color(255, 255, 255));
        pan_menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(22, 22, 115)));
        pan_menu.setMaximumSize(new java.awt.Dimension(32767, 47));
        pan_menu.setMinimumSize(new java.awt.Dimension(0, 47));

        btn_catego.setBackground(new java.awt.Color(226, 232, 240));
        btn_catego.setForeground(new java.awt.Color(255, 255, 255));
        btn_catego.setText("النوعية -  العلامة التجارية");
        btn_catego.setColor1(new java.awt.Color(226, 232, 240));
        btn_catego.setColor2(new java.awt.Color(226, 232, 240));
        btn_catego.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_catego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_catego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_catego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoActionPerformed(evt);
            }
        });

        btn_produit.setBackground(new java.awt.Color(0, 204, 204));
        btn_produit.setForeground(new java.awt.Color(255, 255, 255));
        btn_produit.setText("المنتجات");
        btn_produit.setColor1(new java.awt.Color(255, 255, 255));
        btn_produit.setColor2(new java.awt.Color(0, 204, 204));
        btn_produit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_produit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_produit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_menuLayout = new javax.swing.GroupLayout(pan_menu);
        pan_menu.setLayout(pan_menuLayout);
        pan_menuLayout.setHorizontalGroup(
            pan_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_catego, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pan_menuLayout.setVerticalGroup(
            pan_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pan_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_catego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(pan_menu);

        pan_centre.setBackground(new java.awt.Color(255, 255, 255));
        pan_centre.setLayout(new java.awt.CardLayout());
        add(pan_centre);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produitActionPerformed

        setMenu(pan_menu, btn_produit);
        setForm( pan_produit);
        pan_produit.setProduitsOnTab();

    }//GEN-LAST:event_btn_produitActionPerformed

    private void btn_categoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoActionPerformed
        setMenu(pan_menu, btn_catego);
        setForm( pan_categorie);
        pan_categorie.setCategoriesOnTab();
    }//GEN-LAST:event_btn_categoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.button btn_catego;
    private material.design.button btn_produit;
    private javax.swing.JPanel pan_centre;
    private javax.swing.JPanel pan_menu;
    // End of variables declaration//GEN-END:variables
}
