/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

/**
 *
 * @author pc
 */
public class panSetting extends javax.swing.JPanel {

    /**
     * Creates new form panSetting
     */
    public panSetting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button7 = new material.design.button();
        button9 = new material.design.button();
        button10 = new material.design.button();
        button1 = new material.design.button();
        button2 = new material.design.button();
        button3 = new material.design.button();
        button4 = new material.design.button();

        setBackground(new java.awt.Color(255, 255, 255));

        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-organisation-64 (2).png"))); // NOI18N
        button7.setText("مــؤســســتي");
        button7.setColor1(new java.awt.Color(255, 255, 255));
        button7.setColor2(new java.awt.Color(0, 0, 102));
        button7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-groupe-d'utilisateurs-64 (1).png"))); // NOI18N
        button9.setText("دخـول و خــروج المستخــدمــيـن");
        button9.setColor1(new java.awt.Color(250, 250, 250));
        button9.setColor2(new java.awt.Color(102, 102, 102));
        button9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button10.setForeground(new java.awt.Color(255, 255, 255));
        button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warning (1).png"))); // NOI18N
        button10.setText("سجل الأخطاء");
        button10.setColor1(new java.awt.Color(250, 250, 250));
        button10.setColor2(new java.awt.Color(204, 204, 255));
        button10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/utilisateur.png"))); // NOI18N
        button1.setText("المـسـتـخـدمون");
        button1.setColor1(new java.awt.Color(255, 255, 255));
        button1.setColor2(new java.awt.Color(214, 214, 25));
        button1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-supprimer-pour-toujours-48.png"))); // NOI18N
        button2.setText(" المحذوفات");
        button2.setColor1(new java.awt.Color(255, 255, 255));
        button2.setColor2(new java.awt.Color(255, 153, 255));
        button2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/network_873760.png"))); // NOI18N
        button3.setText("نسخ احتياطي لقاعدة البيانات");
        button3.setColor1(new java.awt.Color(255, 255, 255));
        button3.setColor2(new java.awt.Color(0, 153, 153));
        button3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/foreign-language_8495095.png"))); // NOI18N
        button4.setText("الـلـغـة");
        button4.setColor1(new java.awt.Color(255, 255, 255));
        button4.setColor2(new java.awt.Color(153, 153, 255));
        button4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(button10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
    }//GEN-LAST:event_button7ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
    }//GEN-LAST:event_button10ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.button button1;
    private material.design.button button10;
    private material.design.button button2;
    private material.design.button button3;
    private material.design.button button4;
    private material.design.button button7;
    private material.design.button button9;
    // End of variables declaration//GEN-END:variables
}
