/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package material.design;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 *
 * @author client
 */
public class PanelAction1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction1() {
        initComponents();
        
    }
       

    
     public void initEvent(TableActionEvent event, int row,JTable table,int col) {
        buttonRounder1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
                buttonRounder1.setSelected(true);
                if(buttonRounder1.getIcon()!=null ) buttonRounder1.setIcon(null);
                else  buttonRounder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-coche-emoji-32.png"))); // NOI18N

//                int nb_items = Integer.parseInt(table.getValueAt(row, col).toString());
//                table.setValueAt(nb_items+1, row, col);
            }
        });
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRounder1 = new material.design.buttonRounder();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonRounder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-coche-emoji-32.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(buttonRounder1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonRounder1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder buttonRounder1;
    // End of variables declaration//GEN-END:variables
}
