/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import DialogFram.Exite;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.EntrepriseDAOImpl;
import entity.Entreprise;
import entity.KeyboardLanguage;
import home.HomeForm;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.awt.im.InputContext;
import java.sql.Connection;
import java.util.Locale;
import javax.swing.SwingUtilities;

/**
 *
 * @author pc
 */
public class AddCompany extends javax.swing.JDialog {

    Connection connection;
    HomeForm homeForm;
    Exite exite;
    EntrepriseDAOImpl entrepriseDAOImpl;

    public AddCompany(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.homeForm = (HomeForm) parent;
        initComponents();
        setLocationRelativeTo(this.homeForm);
        exite = new Exite(this, homeForm);
        connection = DatabaseConnection.getInstance().getConnection();
        entrepriseDAOImpl = new EntrepriseDAOImpl(connection);
        matricul.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adress = new ui.card.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_fr_entrepr = new ui.card.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom_entrepr_ar = new ui.card.TextFieldRound();
        tel = new ui.card.TextFieldRound();
        btn_annuler = new material.design.buttonRounder();
        btn_save = new material.design.buttonRounder();
        jLabel6 = new javax.swing.JLabel();
        matricul = new ui.card.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new ui.card.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        adress.setBorder(null);
        adress.setForeground(new java.awt.Color(0, 0, 0));
        adress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        adress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adressFocusGained(evt);
            }
        });
        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        adress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adressKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("اسم الشركة");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("اسم الشركة بالفرنسية");

        nom_fr_entrepr.setBorder(null);
        nom_fr_entrepr.setForeground(new java.awt.Color(0, 0, 0));
        nom_fr_entrepr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_fr_entrepr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nom_fr_entrepr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nom_fr_entreprFocusGained(evt);
            }
        });
        nom_fr_entrepr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_fr_entreprActionPerformed(evt);
            }
        });
        nom_fr_entrepr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nom_fr_entreprKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText(" الهاتف");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("العنوان");

        nom_entrepr_ar.setBorder(null);
        nom_entrepr_ar.setForeground(new java.awt.Color(0, 0, 0));
        nom_entrepr_ar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_entrepr_ar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nom_entrepr_ar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nom_entrepr_arFocusGained(evt);
            }
        });
        nom_entrepr_ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_entrepr_arActionPerformed(evt);
            }
        });
        nom_entrepr_ar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nom_entrepr_arKeyPressed(evt);
            }
        });

        tel.setBorder(null);
        tel.setForeground(new java.awt.Color(0, 0, 0));
        tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telKeyPressed(evt);
            }
        });

        btn_annuler.setBackground(new java.awt.Color(239, 68, 68));
        btn_annuler.setForeground(new java.awt.Color(255, 255, 255));
        btn_annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-cross-mark-48 (1).png"))); // NOI18N
        btn_annuler.setText("الغاء");
        btn_annuler.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(22, 163, 74));
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-coche-emoji-48.png"))); // NOI18N
        btn_save.setText("حفظ");
        btn_save.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("NIF");

        matricul.setBorder(null);
        matricul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricul.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        matricul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculActionPerformed(evt);
            }
        });
        matricul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculKeyPressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(43, 43, 140));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("إضافة  شركة جديدة");
        jLabel7.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("البريد الالكتروني");

        email.setBorder(null);
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel2)
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nom_fr_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(nom_entrepr_ar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel3)
                                .addGap(228, 228, 228)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(jLabel9))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btn_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_fr_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_entrepr_ar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    private void nom_fr_entreprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_fr_entreprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_fr_entreprActionPerformed

    private void nom_entrepr_arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_entrepr_arActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_entrepr_arActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        this.dispose();

    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (nom_entrepr_ar.getText().isEmpty()) {
            exite.showMessageDialog("خــطـأ", "تأكد من ادخال المـعلـومـات");
            return;
        }
        Entreprise entreprise = new Entreprise(0, nom_entrepr_ar.getText(), nom_fr_entrepr.getText(), matricul.getText(), adress.getText(), tel.getText(), email.getText());
        Entreprise entrepriseExist =entrepriseDAOImpl.getEntrepriseParName(entreprise.getNom_ar());
         if (entrepriseExist!=null) {
            exite.showMessageDialog("تنبيه", "تأكد من اسم الشركة فهو موجود مسبقا ");
            return;
        }
        if (new EntrepriseDAOImpl(connection).save(entreprise) > 0) {
            this.dispose();
            new ValidationMessageDialog(this, homeForm).showMessage("تأكيد", "تـم إضـافـة الشـركـة بـنـجـاح ");
            homeForm.getPan_Entreprise().setEntreprisesOnTab();

        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void matriculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculActionPerformed

    }//GEN-LAST:event_matriculActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nom_entrepr_arKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_entrepr_arKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            nom_fr_entrepr.requestFocusInWindow();
        }
    }//GEN-LAST:event_nom_entrepr_arKeyPressed

    private void matriculKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            nom_entrepr_ar.requestFocusInWindow();
        }
    }//GEN-LAST:event_matriculKeyPressed

    private void nom_fr_entreprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_fr_entreprKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            adress.requestFocusInWindow();
        }
    }//GEN-LAST:event_nom_fr_entreprKeyPressed

    private void adressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            tel.requestFocusInWindow();
        }
    }//GEN-LAST:event_adressKeyPressed

    private void telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            email.requestFocusInWindow();
        }
    }//GEN-LAST:event_telKeyPressed

    private void nom_fr_entreprFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nom_fr_entreprFocusGained
        java.awt.im.InputContext systemInputContext = java.awt.im.InputContext.getInstance();
        Locale currentLocale = systemInputContext.getLocale();

        String currentSystemLang = (currentLocale != null) ? currentLocale.getLanguage() : "";

        if (currentSystemLang.equalsIgnoreCase("fr")) {
            System.out.println("La lang et  1: "+currentSystemLang);
            return;
        }
        try {
            Robot robot = new Robot();
            boolean found= true;
            while (found) {
                // استخدام Win + Space بدلاً من Alt + Shift لضمان التنقل الصحيح في Win 11
                robot.keyPress(java.awt.event.KeyEvent.VK_WINDOWS);
                robot.keyPress(java.awt.event.KeyEvent.VK_SPACE);
                robot.keyRelease(java.awt.event.KeyEvent.VK_SPACE);
                robot.keyRelease(java.awt.event.KeyEvent.VK_WINDOWS);

          //      Thread.sleep(250);

                // 3. قراءة اللغة الجديدة المحددة في النظام
                java.awt.im.InputContext systemIC = java.awt.im.InputContext.getInstance();
                Locale currentLocaleNew = systemIC.getLocale();
                String currentLangNew = (currentLocaleNew != null) ? currentLocaleNew.getLanguage() : "";
                if (currentLangNew.equalsIgnoreCase("fr") ||currentLangNew.equals(currentSystemLang) ||currentLangNew.equalsIgnoreCase("en") ) {   
                    System.out.println(" lang : "+currentLangNew );
                    found = false;
                    break;
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

       
//nom_fr_entrepr.requestFocusInWindow();
//    InputContext ic = nom_fr_entrepr.getInputContext();
//
//    if (ic != null) {
//        // 1. تجربة التغير المباشر أولاً (في حال دعم النظام)
//        boolean foundFr = ic.selectInputMethod(new Locale("fr", "FR")) || ic.selectInputMethod(new Locale("fr"));
//
//        if (foundFr) {
//            return; // تم التحويل للفرنسية فوراً
//        }
//
//        // 2. حفظ اللغة الأولى قبل التبديل (مثل "en")
//        Locale initialLocale = ic.getLocale();
//        String startLang = (initialLocale != null) ? initialLocale.getLanguage() : "";
//
//        try {
//            Robot robot = new Robot();
//            int attempts = 0;
//            int maxLanguages = 6; // حد أقصى للغات المثبتة في الويندوز
//
//            while (attempts < maxLanguages) {
//                // استخدام Win + Space بدلاً من Alt + Shift لضمان التنقل الصحيح في Win 11
//                robot.keyPress(java.awt.event.KeyEvent.VK_WINDOWS);
//                robot.keyPress(java.awt.event.KeyEvent.VK_SPACE);
//                robot.keyRelease(java.awt.event.KeyEvent.VK_SPACE);
//                robot.keyRelease(java.awt.event.KeyEvent.VK_WINDOWS);
//
//                // مهلة 250 مللي ثانية ليقوم الويندوز بتحديث حقل النص باللغة الجديدة
//                Thread.sleep(250);
//
//                // قراءة اللغة الجديدة بعد التبديل
//                Locale currentLocale = ic.getLocale();
//                String currentLang = (currentLocale != null) ? currentLocale.getLanguage() : "";
//
//                // الشرط الأول: إذا وصل للغة الفرنسية -> نجاح وخروج
//                if (currentLang.equalsIgnoreCase("fr")) {
//                    foundFr = true;
//                    break;
//                }
//
//                // الشرط الثاني: إذا عبر على العربية وتخطاها وعاد مجدداً لـ "en" (اللغة الأولى)
//                // بشرط أن يكون قام بتجربة التبديل مرتين على الأقل (attempts > 0)
//                if (attempts > 0 && currentLang.equalsIgnoreCase(startLang)) {
//                    foundFr = false; // أكمل دورة كاملة دون العثور على الفرنسية
//                    break;
//                }
//
//                attempts++;
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        // 3. إظهار رسالة التنبيه إذا عاد لنفس اللغة ولم يجد الفرنسية
//        if (!foundFr) {
//            javax.swing.JOptionPane.showMessageDialog(
//                null, 
//                "اللغة الفرنسية غير مثبتة في الويندوز!\nيرجى إضافتها من إعدادات Windows (Language Settings).", 
//                "تنبيه - لغة الإدخال", 
//                javax.swing.JOptionPane.WARNING_MESSAGE
//            );
//        }
//    }
//});

//    SwingUtilities.invokeLater(() -> {
//    nom_fr_entrepr.requestFocusInWindow();
//    
//    InputContext ic = nom_fr_entrepr.getInputContext();
//    if (ic != null) {
//        boolean success = false;
//        
//        // 1. تجربة التغيير المباشر لفرنسا
//        success = ic.selectInputMethod(new Locale("fr", "FR"));
//        
//        // 2. إذا لم تنجح، تجربة لغة فرنسية عامة
//        if (!success) {
//            success = ic.selectInputMethod(new Locale("fr"));
//        }
//        
//        // 3. البحث في كافة اللغات المتاحة في الكيبورد حتى إيجاد الفرنسية
//        if (!success) {
//            Locale[] availableLocales = Locale.getAvailableLocales();
//            for (Locale loc : availableLocales) {
//                if (loc.getLanguage().equalsIgnoreCase("fr")) {
//                    if (ic.selectInputMethod(loc)) {
//                        break; // تم العثور على الفرنسية وتطبيقها بنجاح
//                    }
//                }
//            }
//        }
//    }
//});

    }//GEN-LAST:event_nom_fr_entreprFocusGained

    private void nom_entrepr_arFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nom_entrepr_arFocusGained
        nom_entrepr_ar.getInputContext().selectInputMethod(new Locale("Fr"));
    }//GEN-LAST:event_nom_entrepr_arFocusGained

    private void adressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusGained
        // TODO add your handling code here:
        adress.getInputContext().selectInputMethod(new Locale("ar"));

    }//GEN-LAST:event_adressFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        adress.getInputContext().selectInputMethod(new Locale("fr"));
        System.out.println("test focus gqined");
    }//GEN-LAST:event_emailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCompany dialog = new AddCompany(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.card.TextFieldRound adress;
    private material.design.buttonRounder btn_annuler;
    private material.design.buttonRounder btn_save;
    private ui.card.TextFieldRound email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private ui.card.TextFieldRound matricul;
    private ui.card.TextFieldRound nom_entrepr_ar;
    private ui.card.TextFieldRound nom_fr_entrepr;
    private ui.card.TextFieldRound tel;
    // End of variables declaration//GEN-END:variables
}
