/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import config.DatabaseConnection;
import dao.impl.ProduitDAOImpl;
import entity.Categorie;
import entity.Nomber;
import entity.Produit;
import java.awt.Component;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import material.design.designeTable;

/**
 *
 * @author pc
 */
public class AddNewProduit extends javax.swing.JDialog {

     DecimalFormat formatter = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(Locale.US));    
     Connection connection;
     ProduitDAOImpl produitDAOImpl;
     AchatDetaillForm achatDetaillForm;
    public AddNewProduit(AchatDetaillForm  parent, boolean modal) {
        super(parent, modal);
        this.achatDetaillForm=  parent;
        connection = DatabaseConnection.getInstance().getConnection();
        produitDAOImpl= new ProduitDAOImpl(connection);
        initComponents();
       this.setLocationRelativeTo(null);
        new designeTable().setDesignTable(tabProduit, jScrollPane1);
 
        setProduitsOnTab();
        
    } 
    
     public void setProduitsOnTab() {
        DefaultTableModel model = (DefaultTableModel) tabProduit.getModel();
        model.setRowCount(0);
        List<Produit> produits = produitDAOImpl.findAll();
        String marque = "";
        for (Produit produit : produits) {
            int id = produit.getId();
            String desg = produit.getDesignation();
            Categorie categorie = produit.getCategorie();
            if (categorie != null) {
                marque = categorie.getNomCategorie();
            }
            double prix_vent = produit.getPrix_vente();
            int qt = produit.getQty(); 
            model.addRow(new Object[]{id, formatter.format(prix_vent),
                marque, desg});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tableScrollButton3 = new ui.table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProduit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_searcP = new material.design.SearchTextRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(58, 58, 173));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("إضـافـة مـنـتـج جـديـــد");
        jLabel2.setOpaque(true);

        tabProduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "السعر", "النوعية", "المنتج"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabProduit);

        tableScrollButton3.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("الــمنـــتــجـــات ( انقر مرتين للإضافة)");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-panier-chargé-64.png"))); // NOI18N

        txt_searcP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_searcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searcPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tableScrollButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(txt_searcP, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_searcP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(tableScrollButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searcPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searcPActionPerformed

    private void tabProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProduitMouseClicked
         if (evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt)) {
            DefaultTableModel model = (DefaultTableModel) achatDetaillForm.getTab().getModel();
            int selectedRow = tabProduit.getSelectedRow();
            
                int id = Integer.parseInt(tabProduit.getModel().getValueAt(selectedRow, 0).toString());
                Produit produit = new ProduitDAOImpl(connection).findById(id);
                           
                int existrow = achatDetaillForm.existProduitAchat(produit);
                String marque = "";
                String desg = produit.getDesignation();
                Categorie categorie = produit.getCategorie();

                if (categorie != null) {
                    marque = categorie.getNomCategorie();
                }
                if (existrow==-1){
                double prix_vent = produit.getPrix_vente();

                model.addRow(new Object[]{0,formatter.format(prix_vent),1,formatter.format( prix_vent),
                marque, desg,produit.getId()});
                }else{
                    int idAchatDetaill= (int) achatDetaillForm.getTab().getModel().getValueAt(existrow, 0);
                   
                    if(idAchatDetaill ==0){
                        int Qt= (int) achatDetaillForm.getTab().getModel().getValueAt(existrow, 2) + 1;
                        double prix_unitaire = new Nomber().getNbDouble( achatDetaillForm.getTab().getModel().getValueAt(existrow,3).toString());
                          double prix_Total = prix_unitaire * Qt;

                         model.setValueAt(Qt, existrow, 2);
                        model.setValueAt( formatter.format(prix_Total),existrow,1);
                    }else{
                   double prix_vent = produit.getPrix_vente();
                model.addRow(new Object[]{0,formatter.format(prix_vent),1,formatter.format( prix_vent),
                marque, desg,produit.getId()});
                    }       
                }               
            achatDetaillForm.getBtnSave().setVisible(true);
          achatDetaillForm.getBtnCancel().setVisible(true);
          this.dispose();
            }
        

//      
//        if (evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt)) {
//            DefaultTableModel model = (DefaultTableModel) achatDetaillForm.getTab().getModel();
//            int selectedRow = tabProduit.getSelectedRow();
//            double prixLableTotal= new Nomber().getNbDouble(achatDetaillForm.getLabPrixTotal().getText());
//            if (selectedRow != -1) {
//                int id = Integer.parseInt(tabProduit.getModel().getValueAt(selectedRow, 0).toString());
//                Produit produit = new ProduitDAOImpl(connection).findById(id);
//                String marque = "";
//                String desg = produit.getDesignation();
//                Categorie categorie = produit.getCategorie();
//
//                if (categorie != null) {
//                    marque = categorie.getNomCategorie();
//                }
//                double prix_vent = produit.getPrix_vente();
//
//                model.addRow(new Object[]{id,formatter.format(prix_vent),1,
//                    formatter.format(prix_vent),
//                    marque, desg,produit.getId()});
//                
//                prixLableTotal = prixLableTotal+prix_vent;
//                 achatDetaillForm.getLabPrixTotal().setText(formatter.format(prixLableTotal));
//                 achatDetaillForm.getBtnSave().setVisible(true);
//                 achatDetaillForm.getBtnCancel().setVisible(true);
//                 achatDetaillForm.repaint();
//                 achatDetaillForm.revalidate();
//        }
//            
//        }
    }//GEN-LAST:event_tabProduitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewProduit dialog = new AddNewProduit(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabProduit;
    private ui.table.TableScrollButton tableScrollButton3;
    private material.design.SearchTextRound txt_searcP;
    // End of variables declaration//GEN-END:variables
}
