/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.CategorieDAOImpl;
import dao.impl.ProduitDAOImpl;
import entity.Categorie;
import entity.Nomber;
import entity.Produit;
import home.HomeForm;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;



public class AddProduit extends javax.swing.JDialog {

    Connection connection;
    HomeForm homeForm;
    private Window parentWindow;
    ValidationMessageDialog validationMessageDialog;
    Exite exite;
    MessageDialog messageDialog;
    ProduitDAOImpl produitDAOImpl;
    CategorieDAOImpl categorieDAOImpl;
    DecimalFormat formatter = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(Locale.US));
    Nomber nomber = new Nomber();
    private Dialog parentDialog;


    public AddProduit(Frame parent, boolean modal) {
        super(parent, modal);

        this.parentWindow = parent;

        if (parent instanceof HomeForm) {
            this.homeForm = (HomeForm) parent;
        }
        
        initComponents();
        initData();
    }

    public AddProduit(Dialog parent, boolean modal) {
        super(parent, modal);

        this.parentWindow = parent;
        this.parentDialog = parent;

        if (parent.getOwner() instanceof HomeForm) {
            this.homeForm = (HomeForm) parent.getOwner();
        }

        initComponents();
        initData();
    }

    void initData() {
        setLocationRelativeTo(this.homeForm);
        connection = DatabaseConnection.getInstance().getConnection();
        produitDAOImpl = new ProduitDAOImpl(connection);
        categorieDAOImpl = new CategorieDAOImpl(connection);
        validationMessageDialog = new ValidationMessageDialog(this, homeForm);
        exite = new Exite(this, homeForm);
        messageDialog = new MessageDialog(homeForm);
        setInfoCategorie();
        txt_nom.requestFocus();
    }

    public void setInfoCategorie() {
        List<Categorie> categories = new CategorieDAOImpl(connection).findAll();
        if (!categories.isEmpty()) {
            List<String> categoryNames = new ArrayList<>();
            for (Categorie categorie : categories) {
                categoryNames.add(categorie.getNomCategorie());
            }
            
              System.out.println("nom categ = " + categoryNames.size());
        System.out.println("catego  = " + categoryNames);
            
            txt_catego_aut.setDictionary(categoryNames);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_qt = new ui.card.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nom = new ui.card.TextFieldRound();
        txt_prix_achat = new ui.card.TextFieldRound();
        txt_prix_vent = new ui.card.TextFieldRound();
        btnCancel = new material.design.buttonRounder();
        btnSave = new material.design.buttonRounder();
        jLabel7 = new javax.swing.JLabel();
        txt_catego_aut = new ui.autosuggestextefield.AutoSuggestTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_qt.setBorder(null);
        txt_qt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qt.setText("0");
        txt_qt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txt_qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtActionPerformed(evt);
            }
        });
        txt_qt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qtKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("الـنوعـيـة");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("سعر الشراء");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("سعر البيع");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("الكمية");

        txt_nom.setBorder(null);
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomKeyPressed(evt);
            }
        });

        txt_prix_achat.setBorder(null);
        txt_prix_achat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prix_achat.setText("0.0");
        txt_prix_achat.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txt_prix_achat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prix_achatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prix_achatFocusLost(evt);
            }
        });
        txt_prix_achat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prix_achatActionPerformed(evt);
            }
        });
        txt_prix_achat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_prix_achatKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prix_achatKeyTyped(evt);
            }
        });

        txt_prix_vent.setBorder(null);
        txt_prix_vent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prix_vent.setText("0.0");
        txt_prix_vent.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txt_prix_vent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_prix_ventFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prix_ventFocusLost(evt);
            }
        });
        txt_prix_vent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prix_ventActionPerformed(evt);
            }
        });
        txt_prix_vent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_prix_ventKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prix_ventKeyTyped(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(239, 68, 68));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-cross-mark-48 (1).png"))); // NOI18N
        btnCancel.setText("الغاء");
        btnCancel.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(22, 163, 74));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-coche-emoji-48.png"))); // NOI18N
        btnSave.setText("حفظ");
        btnSave.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(43, 43, 140));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("إضافة منتج جديد");
        jLabel7.setOpaque(true);

        txt_catego_aut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_catego_aut.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        txt_catego_aut.setLabelText("النوعية");
        txt_catego_aut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_catego_autKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("اسم المنتج");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(441, 441, 441)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(173, 173, 173)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(txt_prix_vent, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_prix_achat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1)
                                            .addGap(48, 48, 48))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_catego_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(164, 164, 164)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_catego_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addComponent(txt_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_prix_vent, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(txt_prix_achat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txt_nom.getText().isEmpty() || txt_prix_vent.getText().isEmpty()||txt_qt.getText().isEmpty()) {
            exite.showMessageDialog("تنبيه", "تأكد من ادخال المـعلـومـات");
            return;
        }

        if (txt_nom.getText().isEmpty() ||txt_catego_aut.getText().isEmpty() || txt_prix_vent.getText().isEmpty() ) {
            exite.showMessageDialog("تنبيه", "تأكد من ادخال المـعلـومـات");
            return;
        }

        String txt_categ = "";

        Categorie categorie = null;

        //        if(comp_categ.getSelectedIndex() !=-1 ){
        //            txt_categ=comp_categ.getSelectedItem().toString();
        //            categorie = new CategorieDAOImpl(connection).getCategorierParName(txt_categ);
        //
        //         }
        if (!txt_catego_aut.getText().isEmpty()) {
            txt_categ = txt_catego_aut.getText();
            categorie = categorieDAOImpl.getCategorierParName(txt_categ);
            if(categorie==null){
                categorie = new Categorie(0, txt_categ, "");
                categorieDAOImpl.save(categorie);
                categorie = categorieDAOImpl.getCategorierParName(txt_categ);
            }
            
        }
        Produit produitExist = produitDAOImpl.getProduitParNameAndCatego(txt_nom.getText(), categorie);

        if (produitExist != null) {
            exite.showMessageDialog("تنبيه", "المنتج تم حفظه سابقا");
            return;
        }

        int qt = Integer.parseInt(txt_qt.getText());
        double prix_achat = nomber.getNbDouble(txt_prix_achat.getText());
        double prix_vent = nomber.getNbDouble(txt_prix_vent.getText());

        Produit produit = new Produit(0, txt_categ, txt_nom.getText(), txt_categ, categorie, qt, prix_achat, prix_vent);

        // messageDialog.showMessagetoDialog(" مـنـتـج ", "هـل أنت متـأكـد  مـن إضـافـة المـنـتـج");     
        //if (messageDialog.getMessageType() == MessageDialog.MessageType.OK) {
        if (produitDAOImpl.save(produit) > 0) {

            this.dispose();

            if (parentWindow instanceof HomeForm) {

                validationMessageDialog.showMessage("إضـافـة", "تـم إضافة المنتج بنجاح");

                homeForm.getPan_produit().setProduitsOnTab();

            } else {
                validationMessageDialog.showMessagetoDialog("إضـافـة", "تـم إضافة المنتج بنجاح");

                if (parentDialog instanceof Nouvelle_Achat) {
                    ((Nouvelle_Achat) parentDialog).setProduitsOnTab();
                }

                if (homeForm != null) {
                    homeForm.getPan_produit().setProduitsOnTab();
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txt_prix_ventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prix_ventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_ventActionPerformed

    private void txt_prix_achatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prix_achatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_achatActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void comp_categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_categActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_categActionPerformed

    private void txt_qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtActionPerformed

    private void txt_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_catego_aut.requestFocus();
        }
    }//GEN-LAST:event_txt_nomKeyPressed

    private void txt_catego_autKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catego_autKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_qt.requestFocus();
        }
    }//GEN-LAST:event_txt_catego_autKeyPressed

    private void txt_qtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_prix_achat.requestFocus();
        }
    }//GEN-LAST:event_txt_qtKeyPressed

    private void txt_prix_achatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_achatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_prix_vent.requestFocus();
        }
    }//GEN-LAST:event_txt_prix_achatKeyPressed

    private void txt_prix_ventKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_ventKeyPressed
     
    }//GEN-LAST:event_txt_prix_ventKeyPressed

    private void txt_qtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_qtKeyTyped

    private void txt_prix_achatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_achatKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            return;
        }
        if (c == '.' && !txt_prix_achat.getText().contains(".")) {
            return;
        }

        evt.consume();
    }//GEN-LAST:event_txt_prix_achatKeyTyped

    private void txt_prix_ventKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_ventKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            return;
        }
        if (c == '.' && !txt_prix_vent.getText().contains(".")) {
            return;
        }

        evt.consume();

//        char c = evt.getKeyChar();
//    if (Character.isDigit(c)) {
//        return;
//    }
//    if (c == '.' && !txt_prix_vent.getText().contains(".")) {
//        return;
//    }
//    evt.consume();
//    txt_prix_vent.setText(formatter.format(Double.parseDouble(txt_prix_vent.getText())));
    }//GEN-LAST:event_txt_prix_ventKeyTyped

    private void txt_prix_ventFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_ventFocusLost
        String text = txt_prix_vent.getText().trim();
        if (text.isEmpty()) {
            return;
        }

        try {
            // نحذف الفواصل الموجودة
            text = text.replace(",", "");

            double value = Double.parseDouble(text);

            txt_prix_vent.setText(
                    formatter.format(value)
            );

        } catch (NumberFormatException e) {
            // لا نفرغ الحقل
        }
    }//GEN-LAST:event_txt_prix_ventFocusLost

    private void txt_prix_ventFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_ventFocusGained
        String text = txt_prix_vent.getText().trim();
        if (!text.isEmpty()) {
            try {

                double value = Double.parseDouble(
                        text.replace(",", "")
                );

                txt_prix_vent.setText(
                        String.valueOf(value)
                );

                txt_prix_vent.selectAll();

            } catch (NumberFormatException e) {
                // لا شيء
            }
        }
    }//GEN-LAST:event_txt_prix_ventFocusGained

    private void txt_prix_achatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_achatFocusGained
        String text = txt_prix_achat.getText().trim();
        if (!text.isEmpty()) {

            try {

                double value = Double.parseDouble(
                        text.replace(",", "")
                );

                txt_prix_achat.setText(
                        String.valueOf(value)
                );

                txt_prix_achat.selectAll();

            } catch (NumberFormatException e) {
                // لا شيء
            }
        }
    }//GEN-LAST:event_txt_prix_achatFocusGained

    private void txt_prix_achatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_achatFocusLost
        String text = txt_prix_achat.getText().trim();
        if (text.isEmpty()) {
            return;
        }
        try {
            // نحذف الفواصل الموجودة
            text = text.replace(",", "");
            double value = Double.parseDouble(text);
            txt_prix_achat.setText(
                    formatter.format(value)
            );
        } catch (NumberFormatException e) {
            // لا نفرغ الحقل
        }
    }//GEN-LAST:event_txt_prix_achatFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduit dialog = new AddProduit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnCancel;
    private material.design.buttonRounder btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private ui.autosuggestextefield.AutoSuggestTextField txt_catego_aut;
    private ui.card.TextFieldRound txt_nom;
    private ui.card.TextFieldRound txt_prix_achat;
    private ui.card.TextFieldRound txt_prix_vent;
    private ui.card.TextFieldRound txt_qt;
    // End of variables declaration//GEN-END:variables
}
