/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import config.DatabaseConnection;
import dao.impl.UtilisateurDAOImp;
import entity.Utilisateur;
import home.HomeForm;
import java.sql.Connection;

/**
 *
 * @author pc
 */
public class ConfirmationSupprim extends javax.swing.JDialog {

    UtilisateurDAOImp utilisateurDAOImp;
    Connection connection; 
    HomeForm homeForm;
    boolean existUser;
    public ConfirmationSupprim(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.homeForm = (HomeForm) parent;
        existUser = false;
        connection = DatabaseConnection.getInstance().getConnection();
        utilisateurDAOImp = new UtilisateurDAOImp(connection);
        setLocationRelativeTo(this);
        initComponents();
    }

    public boolean isExistUser() {
        return existUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_gradiant1 = new ui.card.pan_gradiant();
        txtMotPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        buttonRounder1 = new material.design.buttonRounder();
        LabError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonRounder2 = new material.design.buttonRounder();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pan_gradiant1.setColor1(new java.awt.Color(1, 1, 86));
        pan_gradiant1.setColor2(new java.awt.Color(84, 84, 190));

        txtMotPass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtMotPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMotPass.setText("000000");
        txtMotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotPassActionPerformed(evt);
            }
        });
        txtMotPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMotPassKeyPressed(evt);
            }
        });
        pan_gradiant1.add(txtMotPass);
        txtMotPass.setBounds(50, 80, 220, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-mot-de-passe-24.png"))); // NOI18N
        pan_gradiant1.add(jLabel2);
        jLabel2.setBounds(280, 80, 30, 30);

        buttonRounder1.setBackground(new java.awt.Color(204, 0, 0));
        buttonRounder1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder1.setText("تأكيد الحذف");
        buttonRounder1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonRounder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder1ActionPerformed(evt);
            }
        });
        pan_gradiant1.add(buttonRounder1);
        buttonRounder1.setBounds(170, 150, 120, 40);

        LabError.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LabError.setForeground(new java.awt.Color(255, 0, 51));
        LabError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pan_gradiant1.add(LabError);
        LabError.setBounds(37, 120, 220, 20);

        jLabel4.setBackground(new java.awt.Color(21, 21, 171));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pan_gradiant1.add(jLabel4);
        jLabel4.setBounds(290, 10, 30, 30);

        buttonRounder2.setBackground(new java.awt.Color(0, 0, 204));
        buttonRounder2.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder2.setText("إلغاء الحذف");
        buttonRounder2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonRounder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder2ActionPerformed(evt);
            }
        });
        pan_gradiant1.add(buttonRounder2);
        buttonRounder2.setBounds(30, 150, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_gradiant1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_gradiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotPassActionPerformed

    }//GEN-LAST:event_txtMotPassActionPerformed

    private void txtMotPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotPassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotPassKeyPressed

    private void buttonRounder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder1ActionPerformed
        String motPass = new String(txtMotPass.getPassword());
        Utilisateur utilisateur1  = utilisateurDAOImp.getUtilisateurParMotPass(motPass);
        System.out.println(motPass);
        System.out.println(""+utilisateur1);
        if(utilisateur1 !=null ){
            existUser=true;
            this.dispose();
        }else{
            LabError.setText("خـطأ في اسـم المستخدم أو كلمة المرور");
        }
    }//GEN-LAST:event_buttonRounder1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        existUser=false;
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void buttonRounder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder2ActionPerformed
        existUser=false;
        this.dispose();
    }//GEN-LAST:event_buttonRounder2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationSupprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationSupprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationSupprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationSupprim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmationSupprim dialog = new ConfirmationSupprim(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabError;
    private material.design.buttonRounder buttonRounder1;
    private material.design.buttonRounder buttonRounder2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private ui.card.pan_gradiant pan_gradiant1;
    private javax.swing.JPasswordField txtMotPass;
    // End of variables declaration//GEN-END:variables
}
