/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import config.DatabaseConnection;
import dao.impl.UtilisateurDAOImp;
import entity.Utilisateur;
import home.HomeForm;
import java.awt.event.KeyEvent;
import java.sql.Connection;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JDialog {

    UtilisateurDAOImp utilisateurDAOImp; 
    Connection connection;
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);       
        initComponents();
        connection= DatabaseConnection.getInstance().getConnection();
       utilisateurDAOImp   = new UtilisateurDAOImp(connection);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pan_gradiant1 = new ui.card.pan_gradiant();
        txtMotPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonRounder1 = new material.design.buttonRounder();
        LabError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(35, 35, 164));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(1, 1, 86));

        pan_gradiant1.setColor1(new java.awt.Color(1, 1, 86));
        pan_gradiant1.setColor2(new java.awt.Color(84, 84, 190));

        txtMotPass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtMotPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotPassActionPerformed(evt);
            }
        });
        txtMotPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMotPassKeyPressed(evt);
            }
        });
        pan_gradiant1.add(txtMotPass);
        txtMotPass.setBounds(40, 200, 220, 30);

        txtUser.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        pan_gradiant1.add(txtUser);
        txtUser.setBounds(40, 150, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-utilisateur-100.png"))); // NOI18N
        pan_gradiant1.add(jLabel1);
        jLabel1.setBounds(110, 50, 110, 90);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-mot-de-passe-24.png"))); // NOI18N
        pan_gradiant1.add(jLabel2);
        jLabel2.setBounds(260, 200, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-utilisateur-sexe-neutre-26.png"))); // NOI18N
        pan_gradiant1.add(jLabel3);
        jLabel3.setBounds(260, 150, 30, 30);

        buttonRounder1.setBackground(new java.awt.Color(21, 21, 143));
        buttonRounder1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounder1.setText("تـسـجـيـل الـدخـول");
        buttonRounder1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonRounder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounder1ActionPerformed(evt);
            }
        });
        pan_gradiant1.add(buttonRounder1);
        buttonRounder1.setBounds(40, 280, 210, 40);

        LabError.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LabError.setForeground(new java.awt.Color(255, 0, 51));
        LabError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pan_gradiant1.add(LabError);
        LabError.setBounds(37, 240, 220, 20);

        jLabel4.setBackground(new java.awt.Color(21, 21, 171));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pan_gradiant1.add(jLabel4);
        jLabel4.setBounds(270, 10, 30, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_gradiant1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_gradiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 374));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRounder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounder1ActionPerformed
        String nom = txtUser.getText();
        String motPass = new String(txtMotPass.getPassword());
        Utilisateur utilisateur  = utilisateurDAOImp.getUtilisateurParNomMotPass(nom , motPass);
        if(utilisateur !=null ){
           this.dispose();
            new splashscreen.SplashScreen(null, true).setVisible(true);
          HomeForm homeForm=  new HomeForm() ;
                homeForm.setVisible(true);
                homeForm.setUser(nom);
        }else{
            LabError.setText("خـطأ في اسـم المستخدم أو كلمة المرور");
        }
        
    }//GEN-LAST:event_buttonRounder1ActionPerformed

    private void txtMotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotPassActionPerformed
         String nom = txtUser.getText();
        String motPass = new String(txtMotPass.getPassword());
        Utilisateur utilisateur  = utilisateurDAOImp.getUtilisateurParNomMotPass(nom , motPass);
        if(utilisateur !=null ){
            this.dispose();
            new splashscreen.SplashScreen(null, true).setVisible(true);
            new HomeForm().setVisible(true);
        }else{
            LabError.setText("خـطأ في اسـم المستخدم أو كلمة المرور");
        }
    }//GEN-LAST:event_txtMotPassActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            txtMotPass.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtMotPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotPassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabError;
    private material.design.buttonRounder buttonRounder1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private ui.card.pan_gradiant pan_gradiant1;
    private javax.swing.JPasswordField txtMotPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
