/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import DialogFram.Exite;
import DialogFram.MessageDialog;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.CategorieDAOImpl;
import dao.impl.ProduitDAOImpl;
import entity.Categorie;
import entity.Nomber;
import entity.Produit;
import home.HomeForm;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author pc
 */
public class ModifyProduit extends javax.swing.JDialog {

    Connection connection;
    HomeForm homeForm;
    Produit produit;
    ValidationMessageDialog validationMessageDialog;
    Exite exite;
    MessageDialog messageDialog;
    DecimalFormat formatter = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(Locale.US));    
    Nomber nomber =new Nomber() ;
    public ModifyProduit(java.awt.Frame parent, boolean modal, Produit produit) {
        super(parent, modal);
        this.homeForm = (HomeForm) parent;
        initComponents();
        setLocationRelativeTo(this.homeForm);
        validationMessageDialog = new ValidationMessageDialog(this, homeForm);
        exite = new Exite(this, homeForm);
        messageDialog = new MessageDialog(this);
        this.produit = produit;
        connection = DatabaseConnection.getInstance().getConnection();
        InitUI();

        txt_nom.requestFocusInWindow();
        txt_catego_aut.setText(produit.getCategorie().getNomCategorie());

    }
    public void InitUI() {
        setInfoProduit();
        setInfoCategirieOnCombox();
    }

    public void setInfoProduit() {
        txt_nom.setText(produit.getDesignation());
        txt_qt.setText(produit.getQty() + "");
        txt_prixVent.setText(produit.getPrix_vente() + "");
        txt_prix_achat.setText(produit.getPrix_achat() + "");
    }

    public void setInfoCategirieOnCombox() {
        List<Categorie> categories = new CategorieDAOImpl(connection).findAll();
        if (categories != null) {
            List<String> categoryNames = new ArrayList<>();

            for (Categorie categorie : categories) {
                categoryNames.add(categorie.getNomCategorie());
            }
            txt_catego_aut.setDictionary(categoryNames);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_qt = new ui.card.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nom = new ui.card.TextFieldRound();
        txt_prix_achat = new ui.card.TextFieldRound();
        txt_prixVent = new ui.card.TextFieldRound();
        btnCancel = new material.design.buttonRounder();
        btnSave = new material.design.buttonRounder();
        jLabel7 = new javax.swing.JLabel();
        txt_catego_aut = new ui.autosuggestextefield.AutoSuggestTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_qt.setBorder(null);
        txt_qt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txt_qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtActionPerformed(evt);
            }
        });
        txt_qt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qtKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("اسم المنتج");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("النوعية");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("سعر الشراء");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("سعر البيع");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("الكمية");

        txt_nom.setBorder(null);
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomKeyPressed(evt);
            }
        });

        txt_prix_achat.setBorder(null);
        txt_prix_achat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prix_achat.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        txt_prix_achat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_prix_achatFocusLost(evt);
            }
        });
        txt_prix_achat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prix_achatActionPerformed(evt);
            }
        });
        txt_prix_achat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_prix_achatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_prix_achatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prix_achatKeyTyped(evt);
            }
        });

        txt_prixVent.setBorder(null);
        txt_prixVent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prixVent.setFont(new java.awt.Font("Cairo", 1, 15)); // NOI18N
        txt_prixVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prixVentActionPerformed(evt);
            }
        });
        txt_prixVent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_prixVentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prixVentKeyTyped(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(239, 68, 68));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-cross-mark-48 (1).png"))); // NOI18N
        btnCancel.setText("الغاء");
        btnCancel.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(22, 163, 74));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-coche-emoji-48.png"))); // NOI18N
        btnSave.setText("حفظ التعديل");
        btnSave.setFont(new java.awt.Font("Cairo", 1, 16)); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(43, 43, 140));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("تــعــديــل المــنــتـــج ");
        jLabel7.setOpaque(true);

        txt_catego_aut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_catego_aut.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txt_catego_aut.setLabelText("النوعية");
        txt_catego_aut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_catego_autActionPerformed(evt);
            }
        });
        txt_catego_aut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_catego_autKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2)
                .addGap(220, 220, 220)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(txt_catego_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(txt_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel4)
                .addGap(185, 185, 185)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt_prixVent, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txt_prix_achat, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_catego_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txt_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_prixVent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prix_achat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void txt_prix_achatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prix_achatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prix_achatActionPerformed

    private void txt_prixVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prixVentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prixVentActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (txt_nom.getText().isEmpty()) {
            new Exite(this, homeForm).showMessage("خــطـأ", "تأكد من ادخال المـعلـومـات");
            return;
        }

        String txt_categ = "";

        Categorie categorie = null;

        if (!txt_catego_aut.getText().isEmpty()) {
            txt_categ = txt_catego_aut.getText();
            categorie = new CategorieDAOImpl(connection).getCategorierParName(txt_categ);

        }
        int qt = Integer.parseInt(txt_qt.getText());
        double prix_achat =nomber.getNbDouble(txt_prix_achat.getText());
        double prix_vent = nomber.getNbDouble(txt_prixVent.getText());
        produit.setDesignation(txt_nom.getText());
        produit.setReference(txt_categ);
        produit.setMarque(txt_categ);
        produit.setCategorie(categorie);
        produit.setPrix_achat(prix_achat);
        produit.setPrix_vente(prix_vent);
        produit.setQty(qt);

        //   messageDialog.ShowConfirmMessageInDialog("تـأكـيد الـتـعـديـل", "هـل أنت متـأكـد مـن تـعـديـل المــنـتـج");
        //    if (messageDialog.getMessageType() == MessageDialog.MessageType.OK) {
        if (new ProduitDAOImpl(connection).update(produit) > 0) {
            this.dispose();
            validationMessageDialog.showMessage("تـعـديــل", "نم تعديل معلومات المنتح بنجاح");
            homeForm.getPan_produit().setProduitsOnTab();

        }
        //    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txt_catego_autActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_catego_autActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_catego_autActionPerformed

    private void txt_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_catego_aut.requestFocusInWindow();
        }
    }//GEN-LAST:event_txt_nomKeyPressed

    private void txt_catego_autKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_catego_autKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_qt.requestFocusInWindow();
        }
    }//GEN-LAST:event_txt_catego_autKeyPressed

    private void txt_qtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_prixVent.requestFocusInWindow();
        }
    }//GEN-LAST:event_txt_qtKeyPressed

    private void txt_prix_achatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_achatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_prix_achat.requestFocusInWindow();
        }
    }//GEN-LAST:event_txt_prix_achatKeyPressed

    private void txt_prix_achatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_achatKeyReleased
                char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        return;
    }
    if (c == '.' && !txt_prix_achat.getText().contains(".")) {
        return;
    }
    evt.consume();
     double value =nomber.getNbDouble(txt_prix_achat.getText());
    txt_prix_achat.setText(formatter.format(value));

    }//GEN-LAST:event_txt_prix_achatKeyReleased

    private void txt_prixVentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prixVentKeyTyped
        char c = evt.getKeyChar();

    if (Character.isDigit(c)) {
        return;
    }

    if (c == '.' && ! txt_prixVent.getText().contains(".")) {
        return;
    }

    evt.consume();
        double value =nomber.getNbDouble( txt_prixVent.getText());
     txt_prixVent.setText(formatter.format(value));
    }//GEN-LAST:event_txt_prixVentKeyTyped

    private void txt_qtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
        evt.consume();
    }
    }//GEN-LAST:event_txt_qtKeyTyped

    private void txt_prix_achatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prix_achatKeyTyped
        char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        return;
    }
    if (c == '.' && !txt_prix_achat.getText().contains(".")) {
        return;
    }
    evt.consume();
     double value =nomber.getNbDouble(txt_prix_achat.getText());
    txt_prix_achat.setText(formatter.format(value));

    }//GEN-LAST:event_txt_prix_achatKeyTyped

    private void txt_prixVentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prixVentKeyReleased

    }//GEN-LAST:event_txt_prixVentKeyReleased

    private void txt_prix_achatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_prix_achatFocusLost
      
    }//GEN-LAST:event_txt_prix_achatFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyProduit dialog = new ModifyProduit(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private material.design.buttonRounder btnCancel;
    private material.design.buttonRounder btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private ui.autosuggestextefield.AutoSuggestTextField txt_catego_aut;
    private ui.card.TextFieldRound txt_nom;
    private ui.card.TextFieldRound txt_prixVent;
    private ui.card.TextFieldRound txt_prix_achat;
    private ui.card.TextFieldRound txt_qt;
    // End of variables declaration//GEN-END:variables
}
