/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import DialogFram.Exite;
import DialogFram.ValidationMessageDialog;
import config.DatabaseConnection;
import dao.impl.EntrepriseDAOImpl;
import entity.Entreprise;
import home.HomeForm;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author pc
 */
public class ModifyCompany extends javax.swing.JDialog {

    Connection connection;
    HomeForm homeForm;
    Entreprise entreprise;

    public ModifyCompany(java.awt.Frame parent, boolean modal, Entreprise entreprise) {
        super(parent,modal);
        this.homeForm = (HomeForm) parent;
        this.entreprise = entreprise;
        initComponents();
        setLocationRelativeTo(this.homeForm);

        connection = DatabaseConnection.getInstance().getConnection();
        InitUI();
        matricul.requestFocus();
    }

    public void InitUI() {
        setInfoEntreprise();
    }

    public void setInfoEntreprise() {
        matricul.setText(entreprise.getDesc());
        nom_entrepr.setText(entreprise.getNom_ar());
        nom_fr_entrepr.setText(entreprise.getNom_fr());
        adress.setText(entreprise.getAdresse());
        tel.setText(entreprise.getTel());
        email.setText(entreprise.getEmail());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adress = new ui.card.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_fr_entrepr = new ui.card.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom_entrepr = new ui.card.TextFieldRound();
        tel = new ui.card.TextFieldRound();
        btnCancel = new material.design.buttonRounder();
        btnSave = new material.design.buttonRounder();
        matricul = new ui.card.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new ui.card.TextFieldRound();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        adress.setBorder(null);
        adress.setForeground(new java.awt.Color(0, 0, 0));
        adress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        adress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adressKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("اسم الشركة");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("اسم الشركة بالفرنسية ");

        nom_fr_entrepr.setBorder(null);
        nom_fr_entrepr.setForeground(new java.awt.Color(0, 0, 0));
        nom_fr_entrepr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_fr_entrepr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nom_fr_entrepr.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        nom_fr_entrepr.setMinimumSize(new java.awt.Dimension(64, 32));
        nom_fr_entrepr.setPreferredSize(new java.awt.Dimension(64, 32));
        nom_fr_entrepr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_fr_entreprActionPerformed(evt);
            }
        });
        nom_fr_entrepr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nom_fr_entreprKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText(" الهاتف");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("العنوان");

        nom_entrepr.setBorder(null);
        nom_entrepr.setForeground(new java.awt.Color(0, 0, 0));
        nom_entrepr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_entrepr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nom_entrepr.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        nom_entrepr.setMinimumSize(new java.awt.Dimension(64, 32));
        nom_entrepr.setPreferredSize(new java.awt.Dimension(64, 32));
        nom_entrepr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_entreprActionPerformed(evt);
            }
        });
        nom_entrepr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nom_entreprKeyPressed(evt);
            }
        });

        tel.setBorder(null);
        tel.setForeground(new java.awt.Color(0, 0, 0));
        tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telKeyPressed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(239, 68, 68));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-cross-mark-48 (1).png"))); // NOI18N
        btnCancel.setText("الغاء");
        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(22, 163, 74));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button/icons8-coche-emoji-48.png"))); // NOI18N
        btnSave.setText("حفظ التعديل");
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        matricul.setBorder(null);
        matricul.setForeground(new java.awt.Color(0, 0, 0));
        matricul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricul.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        matricul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculActionPerformed(evt);
            }
        });
        matricul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculKeyPressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(43, 43, 140));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("تــعــــديــــل  مـعـلـومـات الشــــركــــة ");
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("البريد الالكتروني");

        email.setBorder(null);
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("NIF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(165, 165, 165)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nom_fr_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(nom_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel3)
                .addGap(214, 214, 214)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(jLabel9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(matricul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_fr_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_entrepr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    private void nom_fr_entreprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_fr_entreprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_fr_entreprActionPerformed

    private void nom_entreprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_entreprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_entreprActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (nom_entrepr.getText().isEmpty() && nom_fr_entrepr.getText().isEmpty()) {
            new Exite(this, homeForm).showMessage("خــطـأ", "تأكد من ادخال المـعلـومـات");
            return;
        }
        entreprise.setNom_ar(nom_entrepr.getText());
        entreprise.setNom_fr(nom_fr_entrepr.getText());
        entreprise.setDesc(matricul.getText());
        entreprise.setAdresse(adress.getText());
        entreprise.setTel(tel.getText());
        entreprise.setEmail(email.getText());

        if (new EntrepriseDAOImpl(connection).update(entreprise) > 0) {
            homeForm.getPan_Entreprise().setEntreprisesOnTab();
            this.dispose();
            new ValidationMessageDialog(this, homeForm).showMessage("تأكيد", "نم تعديل الشركة بنجاح ");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void matriculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void matriculKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculKeyPressed
if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB ) {
                    nom_entrepr.requestFocusInWindow();
          }
    }//GEN-LAST:event_matriculKeyPressed

    private void nom_entreprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_entreprKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB ) {
                    nom_fr_entrepr.requestFocusInWindow();
          }
    }//GEN-LAST:event_nom_entreprKeyPressed

    private void nom_fr_entreprKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_fr_entreprKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB ) {
                    adress.requestFocusInWindow();
          }
    }//GEN-LAST:event_nom_fr_entreprKeyPressed

    private void adressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB ) {
                    tel.requestFocusInWindow();
          }
    }//GEN-LAST:event_adressKeyPressed

    private void telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB ) {
                    email.requestFocusInWindow();
          }
    }//GEN-LAST:event_telKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyCompany dialog = new ModifyCompany(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.card.TextFieldRound adress;
    private material.design.buttonRounder btnCancel;
    private material.design.buttonRounder btnSave;
    private ui.card.TextFieldRound email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private ui.card.TextFieldRound matricul;
    private ui.card.TextFieldRound nom_entrepr;
    private ui.card.TextFieldRound nom_fr_entrepr;
    private ui.card.TextFieldRound tel;
    // End of variables declaration//GEN-END:variables
}
