/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.table;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        
        
        // 1. إنشاء المنيو الأفقي

// 2. تجهيز الأيقونات الخاصة بك (يفضل أن تكون بسيطة وحجمها 18x18 أو 20x20 بكسل)
ImageIcon prodIcon = new ImageIcon(getClass().getResource("/icon/facture.png"));
ImageIcon salesIcon = new ImageIcon(getClass().getResource("/icon/facture.png"));
ImageIcon billIcon = new ImageIcon(getClass().getResource("/icon/facture.png"));
ImageIcon settingsIcon = new ImageIcon(getClass().getResource("/icon/facture.png"));

// 3. إضافة التبويبات مع تحديد الأكشن (الحدث) الذي يحدث عند الضغط على كل تبويب
topMenu.addMenuItem("المنتجات", prodIcon, () -> {
    System.out.println("تم فتح صفحة المنتجات");
    // هنا تضع كود فتح أو إظهار لوحة المنتجات (مثلاً jCardLayout.show(panel, "products");)
});

topMenu.addMenuItem("المبيعات", salesIcon, () -> {
    System.out.println("تم فتح صفحة المبيعات");
});

topMenu.addMenuItem("الفواتير", billIcon, () -> {
    System.out.println("تم فتح صفحة الفواتير");
});

topMenu.addMenuItem("الإعدادات", settingsIcon, () -> {
    System.out.println("تم فتح الإعدادات");
});

// 4. إضافة المنيو في أعلى الواجهة تماماً
this.setLayout(new BorderLayout());
this.add(topMenu, BorderLayout.NORTH);
        
        // 1. إنشاء مصفوفة بأسماء الأعمدة بالترتيب العربي (من اليمين لليسار كما في واجهتك)
String[] columns = {"id", "سعر البيع", "سعر الشراء", "العدد", "ref", "النوع", "اسم المنتج"};

// 2. إنشاء الـ Model الافتراضي للجدول واشتراطه لمنع تعديل الخلايا بالكتابة مباشرة
DefaultTableModel model = new DefaultTableModel(columns, 0) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // يمنع المستخدم من الكتابة داخل الجدول مباشرة بالنقرة المزدوجة
    }
};

// 3. ربط الموديل بجدولك المصمم (افترضنا أن اسمه jTable1)
jTable1.setModel(model);

// 4. ملء الجدول ببيانات تجريبية سريعة (نفس بيانات واجهتك)
model.addRow(new Object[]{"2", "11.5", "10.5", "20", "4545", "أجبان", "جبن شيدر"});
model.addRow(new Object[]{"3", "1000.0", "500.5", "30", "2222", "توابل", "ملح يودي"});
model.addRow(new Object[]{"4", "60.0", "50.0", "30", "78545", "خضروات", "طماطم طازجة"});

// 5. تطبيق التنسيق العربي والحديث على الأعمدة العادية (id, سعر البيع, سعر الشراء, العدد, ref, النوع)
CustomTable.IconTableCellRenderer arabicRenderer = new CustomTable.IconTableCellRenderer();

// نمرر الـ Renderer على كل الأعمدة من 0 إلى 5
for (int i = 0; i <= 5; i++) {
    jTable1.getColumnModel().getColumn(i).setCellRenderer(arabicRenderer);
}

// 6. تطبيق الـ Renderer المخصص مع الأيقونة على عمود "اسم المنتج" فقط (العمود رقم 6 والأخير)
// تأكد من وضع أيقونة صغيرة بمقاس 16x16 بكسل في مجلد الصور بمشروعك
ImageIcon productIcon = new ImageIcon(getClass().getResource("/icon/facture.png")); 
CustomTable.IconTableCellRenderer iconRenderer = new CustomTable.IconTableCellRenderer(productIcon);

jTable1.getColumnModel().getColumn(6).setCellRenderer(iconRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCustom1 = new ui.table.TableCustom();
        tableCustom2 = new ui.table.TableCustom();
        tableScrollButton1 = new ui.table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new ui.table.CustomTable();
        topMenu = new ui.menufr.TopNavigationBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private ui.table.CustomTable jTable1;
    private ui.table.TableCustom tableCustom1;
    private ui.table.TableCustom tableCustom2;
    private ui.table.TableScrollButton tableScrollButton1;
    private ui.menufr.TopNavigationBar topMenu;
    // End of variables declaration//GEN-END:variables
}
